import type { Scene } from '../../../../types/story'

export const returnHomeQuestStartScene = 184

type DraftRoute = { flag: string; next: string }
type DraftScene = Omit<Scene, 'next' | 'nextByFlag' | 'fallbackNext'> & {
  id?: string
  next?: string
  nextByFlag?: DraftRoute[]
  fallbackNext?: string
}

const buildScenes = (startIndex: number, drafts: DraftScene[]): Scene[] => {
  const labels = new Map<string, number>()
  drafts.forEach((draft, index) => {
    if (draft.id) labels.set(draft.id, startIndex + index)
  })

  const resolveLabel = (label?: string) => label === undefined ? undefined : labels.get(label)

  return drafts.map(({ id: _id, next, nextByFlag, fallbackNext, ...scene }) => ({
    ...scene,
    next: resolveLabel(next),
    nextByFlag: nextByFlag?.map((route) => ({ flag: route.flag, next: resolveLabel(route.next) ?? startIndex })),
    fallbackNext: resolveLabel(fallbackNext),
  }))
}

const groupMessage = (
  speaker: Scene['speaker'],
  text: string,
  direction: 'incoming' | 'outgoing',
  next?: string,
): DraftScene => ({
  speaker,
  text,
  background: 'dmit-room',
  phoneMessage: { contact: 'Арбековские', direction },
  next,
})

export const returnHomeQuestScenes: Scene[] = buildScenes(returnHomeQuestStartScene, [
  {
    id: 'start',
    speaker: 'Рассказчик',
    text: 'Дверь квартиры Дмитa открывается с тем самым домашним скрипом, который сразу сообщает: тут тебя любят, кормят и обязательно спросят, почему ты опять пришёл не так.',
    left: 'Дмит',
    background: 'home',
    nextByFlag: [
      { flag: 'CHAPTER_1_HELPED_MISHGAN', next: 'director-1' },
      { flag: 'CHAPTER_1_LEFT_MISHGAN', next: 'escaped-1' },
    ],
    fallbackNext: 'escaped-1',
  },
  { id: 'director-1', speaker: 'Рассказчик', text: 'После разговора с директором Дмит возвращается домой позже обычного. Настроение у него такое, будто он отсидел восемь уроков подряд.', left: 'Дмит', right: 'Татьяна', background: 'home', next: 'director-2' },
  { id: 'director-2', speaker: 'Татьяна', text: 'Диня, ты почему так поздно? Я уже начала волноваться!', left: 'Дмит', right: 'Татьяна', next: 'director-3' },
  { id: 'director-3', speaker: 'Дмит', text: 'Да директор задержал.', left: 'Дмит', right: 'Татьяна', next: 'director-4' },
  { id: 'director-4', speaker: 'Татьяна', text: 'Директор?! Господи, что ты опять натворил?', left: 'Дмит', right: 'Татьяна', rightEmotion: 'surprised', next: 'director-5' },
  { id: 'director-5', speaker: 'Дмит', text: 'Да ничё особенного.', left: 'Дмит', right: 'Татьяна', leftEmotion: 'thinking', next: 'director-6' },
  { id: 'director-6', speaker: 'Игорь', text: 'Если директор запомнил твоё имя — значит, особенное.', left: 'Дмит', right: 'Игорь', next: 'director-7' },
  { id: 'director-7', speaker: 'Дмит', text: 'Мы с Мишганом выйти хотели.', left: 'Дмит', right: 'Игорь', next: 'director-8' },
  { id: 'director-8', speaker: 'Игорь', text: 'Вышли?', left: 'Дмит', right: 'Игорь', next: 'director-9' },
  { id: 'director-9', speaker: 'Дмит', text: 'Не совсем.', left: 'Дмит', right: 'Игорь', leftEmotion: 'sad', next: 'director-10' },
  { id: 'director-10', speaker: 'Игорь', text: 'Значит, плохо хотели.', left: 'Дмит', right: 'Игорь', next: 'director-11' },
  { id: 'director-11', speaker: 'Татьяна', text: 'Игорь, не учи ребёнка убегать из школы!', left: 'Игорь', right: 'Татьяна', rightEmotion: 'angry', next: 'director-12' },
  { id: 'director-12', speaker: 'Игорь', text: 'Я учу его доводить дело до конца.', left: 'Игорь', right: 'Татьяна', next: 'director-13' },
  { id: 'director-13', speaker: 'Дмит', text: 'Нас охранник поймал.', left: 'Дмит', right: 'Игорь', next: 'director-14' },
  { id: 'director-14', speaker: 'Игорь', text: 'Тем более. Если начал бежать — не оборачивайся. Кто оборачивается, тот уже сомневается.', left: 'Дмит', right: 'Игорь', next: 'director-15' },
  { id: 'director-15', speaker: 'Татьяна', text: 'Какие ещё советы ты ему даёшь?!', left: 'Игорь', right: 'Татьяна', rightEmotion: 'surprised', next: 'director-16' },
  { id: 'director-16', speaker: 'Игорь', text: 'Мужские.', left: 'Игорь', right: 'Татьяна', next: 'director-17' },
  { id: 'director-17', speaker: 'Дмит', text: 'Мишган обернулся. Он охраннику стойку показывал.', left: 'Дмит', right: 'Игорь', next: 'director-18' },
  { id: 'director-18', speaker: 'Игорь', text: 'Это уже не побег. Это цирк.', left: 'Дмит', right: 'Игорь', next: 'director-19' },
  { id: 'director-19', speaker: 'Татьяна', text: 'Диня, иди раздевайся. И больше никогда так не делай!', left: 'Дмит', right: 'Татьяна', rightEmotion: 'sad', next: 'director-20' },
  { id: 'director-20', speaker: 'Дмит', text: 'Ага.', left: 'Дмит', right: 'Татьяна', leftEmotion: 'sad', next: 'grades-start' },

  { id: 'escaped-1', speaker: 'Рассказчик', text: 'Дмит возвращается домой раньше обычного. Он осторожно открывает дверь и пытается пройти к себе, не привлекая внимания.', left: 'Дмит', background: 'home', next: 'escaped-2' },
  { id: 'escaped-2', speaker: 'Татьяна', text: 'Диня?', left: 'Дмит', right: 'Татьяна', next: 'escaped-3' },
  { id: 'escaped-3', speaker: 'Дмит', text: 'Бля…', left: 'Дмит', right: 'Татьяна', leftEmotion: 'surprised', next: 'escaped-4' },
  { id: 'escaped-4', speaker: 'Татьяна', text: 'Что ты сказал?', left: 'Дмит', right: 'Татьяна', rightEmotion: 'surprised', next: 'escaped-5' },
  { id: 'escaped-5', speaker: 'Дмит', text: 'Говорю: мам, привет.', left: 'Дмит', right: 'Татьяна', next: 'escaped-6' },
  { id: 'escaped-6', speaker: 'Татьяна', text: 'А почему ты так рано?', left: 'Дмит', right: 'Татьяна', next: 'escaped-7' },
  { id: 'escaped-7', speaker: 'Дмит', text: 'Уроки закончились.', left: 'Дмит', right: 'Татьяна', leftEmotion: 'thinking', next: 'escaped-8' },
  { id: 'escaped-8', speaker: 'Игорь', text: 'В это время?', left: 'Дмит', right: 'Игорь', next: 'escaped-9' },
  { id: 'escaped-9', speaker: 'Дмит', text: 'Ну… для меня закончились.', left: 'Дмит', right: 'Игорь', next: 'escaped-10' },
  { id: 'escaped-10', speaker: 'Игорь', text: 'Сам решил?', left: 'Дмит', right: 'Игорь', next: 'escaped-11' },
  { id: 'escaped-11', speaker: 'Дмит', text: 'Типа того.', left: 'Дмит', right: 'Игорь', next: 'escaped-12' },
  { id: 'escaped-12', speaker: 'Игорь', text: 'Смело.', left: 'Дмит', right: 'Игорь', next: 'escaped-13' },
  { id: 'escaped-13', speaker: 'Татьяна', text: 'Игорь!', left: 'Игорь', right: 'Татьяна', rightEmotion: 'angry', next: 'escaped-14' },
  { id: 'escaped-14', speaker: 'Игорь', text: 'Но глупо.', left: 'Игорь', right: 'Татьяна', next: 'escaped-15' },
  { id: 'escaped-15', speaker: 'Дмит', text: 'Мы с Мишганом выйти хотели. Охранник за нами побежал.', left: 'Дмит', right: 'Игорь', next: 'escaped-16' },
  { id: 'escaped-16', speaker: 'Татьяна', text: 'Господи!', left: 'Дмит', right: 'Татьяна', rightEmotion: 'surprised', next: 'escaped-17' },
  { id: 'escaped-17', speaker: 'Игорь', text: 'И что?', left: 'Дмит', right: 'Игорь', next: 'escaped-18' },
  { id: 'escaped-18', speaker: 'Дмит', text: 'Мишган упал.', left: 'Дмит', right: 'Игорь', leftEmotion: 'sad', next: 'escaped-19' },
  { id: 'escaped-19', speaker: 'Игорь', text: 'А ты?', left: 'Дмит', right: 'Игорь', next: 'escaped-20' },
  { id: 'escaped-20', speaker: 'Дмит', text: 'А я убежал.', left: 'Дмит', right: 'Игорь', leftEmotion: 'sad', next: 'escaped-21' },
  { id: 'escaped-21', speaker: 'Игорь', text: 'Плохо.', left: 'Дмит', right: 'Игорь', next: 'escaped-22' },
  { id: 'escaped-22', speaker: 'Дмит', text: 'Чё плохо? Зато меня не поймали.', left: 'Дмит', right: 'Игорь', leftEmotion: 'angry', next: 'escaped-23' },
  { id: 'escaped-23', speaker: 'Игорь', text: 'Сегодня ты бросил друга охраннику. Завтра кто-то бросит тебя людям посерьёзнее.', left: 'Дмит', right: 'Игорь', next: 'escaped-24' },
  { id: 'escaped-24', speaker: 'Дмит', text: 'Он сам сказал мне валить.', left: 'Дмит', right: 'Игорь', next: 'escaped-25' },
  { id: 'escaped-25', speaker: 'Игорь', text: 'Люди много чего говорят, когда лежат на земле. Смотри на поступки, а не на слова.', left: 'Дмит', right: 'Игорь', next: 'escaped-26' },
  { id: 'escaped-26', speaker: 'Татьяна', text: 'Зато Диня дома и с ним всё хорошо.', left: 'Игорь', right: 'Татьяна', rightEmotion: 'sad', next: 'escaped-27' },
  { id: 'escaped-27', speaker: 'Игорь', text: 'Сегодня — хорошо.', left: 'Игорь', right: 'Татьяна', next: 'escaped-28' },
  { id: 'escaped-28', speaker: 'Дмит', text: 'Да понял я.', left: 'Дмит', right: 'Игорь', leftEmotion: 'sad', next: 'escaped-29' },
  { id: 'escaped-29', speaker: 'Игорь', text: 'Не понял. Когда поймёшь — извинишься перед другом.', left: 'Дмит', right: 'Игорь', next: 'escaped-30' },
  { id: 'escaped-30', speaker: 'Дмит', text: 'Потом.', left: 'Дмит', right: 'Игорь', next: 'escaped-31' },
  { id: 'escaped-31', speaker: 'Игорь', text: 'Потом обычно поздно.', left: 'Дмит', right: 'Игорь', next: 'grades-start' },

  { id: 'grades-start', speaker: 'Татьяна', text: 'Диня, подожди. Тебе сегодня оценки ставили?', left: 'Дмит', right: 'Татьяна', background: 'home', next: 'grades-2' },
  { id: 'grades-2', speaker: 'Дмит', text: 'Мам…', left: 'Дмит', right: 'Татьяна', leftEmotion: 'sad', next: 'grades-choice' },
  {
    id: 'grades-choice',
    speaker: 'Татьяна',
    text: 'Что — мам? Я просто спрашиваю.',
    left: 'Дмит',
    right: 'Татьяна',
    choices: [
      { label: 'Да нормально всё. Ничего не ставили.', next: returnHomeQuestStartScene, failNext: returnHomeQuestStartScene, requires: { charisma: 5 }, effects: { experience: 4, flags: ['CHAPTER_1_LIED_TO_PARENTS'] }, failureEffects: { experience: 2, flags: ['CHAPTER_1_LIE_FAILED'] }, failureText: 'Дмит пытается соврать, но голос делает кульбит, глаза бегут в разные стороны, и родители слышат ложь раньше слов.' },
      { label: 'Поставили. Могу сказать.', next: returnHomeQuestStartScene, effects: { experience: 8, flags: ['CHAPTER_1_TOLD_PARENTS_GRADE'] } },
    ],
  },
  { id: 'lie-1', speaker: 'Дмит', text: 'Да нормально всё. Ничего не ставили.', left: 'Дмит', right: 'Татьяна', next: 'lie-2' },
  { id: 'lie-2', speaker: 'Татьяна', text: 'Совсем ничего?', left: 'Дмит', right: 'Татьяна', next: 'lie-3' },
  { id: 'lie-3', speaker: 'Дмит', text: 'Совсем.', left: 'Дмит', right: 'Татьяна', next: 'lie-4' },
  { id: 'lie-4', speaker: 'Игорь', text: 'Глаза бегают.', left: 'Дмит', right: 'Игорь', next: 'lie-5' },
  { id: 'lie-5', speaker: 'Дмит', text: 'Куда они бегают?', left: 'Дмит', right: 'Игорь', next: 'lie-6' },
  { id: 'lie-6', speaker: 'Игорь', text: 'От правды.', left: 'Дмит', right: 'Игорь', next: 'lie-7' },
  { id: 'lie-7', speaker: 'Татьяна', text: 'Игорь, не дави на него.', left: 'Игорь', right: 'Татьяна', next: 'lie-8' },
  { id: 'lie-8', speaker: 'Дмит', text: 'Можно я пойду?', left: 'Дмит', right: 'Татьяна', next: 'lie-9' },
  { id: 'lie-9', speaker: 'Татьяна', text: 'Иди. Но дневник вечером покажешь.', left: 'Дмит', right: 'Татьяна', next: 'lie-10' },
  { id: 'lie-10', speaker: 'Рассказчик', text: 'Дмит уходит в комнату. Дневник в его рюкзаке становится тяжелее примерно на двадцать килограммов.', left: 'Дмит', background: 'dmit-room', next: 'cleanup-start' },

  {
    id: 'truth-router',
    speaker: 'Игорь',
    text: 'Отвечай прямо.',
    left: 'Дмит',
    right: 'Игорь',
    nextByFlag: [
      { flag: 'geography-grade-5', next: 'grade5-1' },
      { flag: 'geography-grade-4', next: 'grade4-1' },
      { flag: 'geography-grade-3', next: 'grade3-1' },
      { flag: 'geography-grade-2', next: 'grade2-1' },
      { flag: 'control-work-caught', next: 'grade2-1' },
    ],
    fallbackNext: 'grade2-1',
  },
  { id: 'grade2-1', speaker: 'Дмит', text: 'Два получил.', left: 'Дмит', right: 'Татьяна', leftEmotion: 'sad', next: 'grade2-2' },
  { id: 'grade2-2', speaker: 'Татьяна', text: 'Диня… Ну как же так?', left: 'Дмит', right: 'Татьяна', rightEmotion: 'sad', next: 'grade2-3' },
  { id: 'grade2-3', speaker: 'Дмит', text: 'Да вопрос дебильный был.', left: 'Дмит', right: 'Игорь', next: 'grade2-4' },
  { id: 'grade2-4', speaker: 'Игорь', text: 'Какой?', left: 'Дмит', right: 'Игорь', next: 'grade2-5' },
  { id: 'grade2-5', speaker: 'Дмит', text: 'Где находится какая-то страна.', left: 'Дмит', right: 'Игорь', next: 'grade2-6' },
  { id: 'grade2-6', speaker: 'Игорь', text: 'И где она?', left: 'Дмит', right: 'Игорь', next: 'grade2-7' },
  { id: 'grade2-7', speaker: 'Дмит', text: 'Да хрен её знает.', left: 'Дмит', right: 'Игорь', next: 'grade2-8' },
  { id: 'grade2-8', speaker: 'Игорь', text: 'Значит, вопрос был нормальный.', left: 'Дмит', right: 'Игорь', next: 'grade2-9' },
  { id: 'grade2-9', speaker: 'Татьяна', text: 'Хорошо, что признался. Но двойку надо исправить.', left: 'Дмит', right: 'Татьяна', rightEmotion: 'sad', next: 'grade2-10' },
  { id: 'grade2-10', speaker: 'Дмит', text: 'Исправлю.', left: 'Дмит', right: 'Татьяна', next: 'grade2-11' },
  { id: 'grade2-11', speaker: 'Игорь', text: 'Не обещай. Сделай.', left: 'Дмит', right: 'Игорь', next: 'cleanup-start' },

  { id: 'grade3-1', speaker: 'Дмит', text: 'Три получил.', left: 'Дмит', right: 'Татьяна', next: 'grade3-2' },
  { id: 'grade3-2', speaker: 'Татьяна', text: 'Опять тройка…', left: 'Дмит', right: 'Татьяна', rightEmotion: 'sad', next: 'grade3-3' },
  { id: 'grade3-3', speaker: 'Дмит', text: 'Но не два же.', left: 'Дмит', right: 'Татьяна', next: 'grade3-4' },
  { id: 'grade3-4', speaker: 'Игорь', text: 'Средне — это когда ты сделал половину дела и устал.', left: 'Дмит', right: 'Игорь', next: 'grade3-5' },
  { id: 'grade3-5', speaker: 'Дмит', text: 'Ну я почти так и сделал.', left: 'Дмит', right: 'Игорь', next: 'grade3-6' },
  { id: 'grade3-6', speaker: 'Татьяна', text: 'Ты ведь можешь учиться лучше.', left: 'Дмит', right: 'Татьяна', next: 'grade3-7' },
  { id: 'grade3-7', speaker: 'Дмит', text: 'Все так говорят.', left: 'Дмит', right: 'Татьяна', next: 'grade3-8' },
  { id: 'grade3-8', speaker: 'Игорь', text: 'Потому что это правда.', left: 'Дмит', right: 'Игорь', next: 'grade3-9' },
  { id: 'grade3-9', speaker: 'Дмит', text: 'Я зато честно сказал.', left: 'Дмит', right: 'Игорь', next: 'grade3-10' },
  { id: 'grade3-10', speaker: 'Игорь', text: 'За это уважаю.', left: 'Дмит', right: 'Игорь', next: 'grade3-11' },
  { id: 'grade3-11', speaker: 'Татьяна', text: 'И я рада, что ты не стал скрывать. Но следующая оценка должна быть выше.', left: 'Дмит', right: 'Татьяна', next: 'grade3-12' },
  { id: 'grade3-12', speaker: 'Игорь', text: 'Не «ладно». Четыре.', left: 'Дмит', right: 'Игорь', next: 'cleanup-start' },

  { id: 'grade4-1', speaker: 'Дмит', text: 'Четыре поставили.', left: 'Дмит', right: 'Татьяна', leftEmotion: 'happy', next: 'grade4-2' },
  { id: 'grade4-2', speaker: 'Татьяна', text: 'Четыре? Динечка, молодец!', left: 'Дмит', right: 'Татьяна', rightEmotion: 'happy', next: 'grade4-3' },
  { id: 'grade4-3', speaker: 'Дмит', text: 'Чё сразу Динечка?', left: 'Дмит', right: 'Татьяна', next: 'grade4-4' },
  { id: 'grade4-4', speaker: 'Игорь', text: 'Сам получил?', left: 'Дмит', right: 'Игорь', next: 'grade4-5' },
  { id: 'grade4-5', speaker: 'Дмит', text: 'Сам.', left: 'Дмит', right: 'Игорь', next: 'grade4-6' },
  { id: 'grade4-6', speaker: 'Игорь', text: 'Не списал?', left: 'Дмит', right: 'Игорь', next: 'grade4-7' },
  { id: 'grade4-7', speaker: 'Дмит', text: 'Почти не списал.', left: 'Дмит', right: 'Игорь', leftEmotion: 'thinking', next: 'grade4-8' },
  { id: 'grade4-8', speaker: 'Игорь', text: 'Что значит «почти»?', left: 'Дмит', right: 'Игорь', next: 'grade4-9' },
  { id: 'grade4-9', speaker: 'Дмит', text: 'Ну подсмотрел одну букву.', left: 'Дмит', right: 'Игорь', next: 'grade4-10' },
  { id: 'grade4-10', speaker: 'Игорь', text: 'Одну букву можно.', left: 'Дмит', right: 'Игорь', next: 'grade4-11' },
  { id: 'grade4-11', speaker: 'Татьяна', text: 'Игорь!', left: 'Игорь', right: 'Татьяна', rightEmotion: 'surprised', next: 'grade4-12' },
  { id: 'grade4-12', speaker: 'Игорь', text: 'Результат есть. Но не расслабляйся. Одна удачная сделка ещё не делает человека большим.', left: 'Дмит', right: 'Игорь', next: 'cleanup-start' },

  { id: 'grade5-1', speaker: 'Дмит', text: 'Пять получил.', left: 'Дмит', right: 'Татьяна', leftEmotion: 'happy', next: 'grade5-2' },
  { id: 'grade5-2', speaker: 'Татьяна', text: 'Что?', left: 'Дмит', right: 'Татьяна', rightEmotion: 'surprised', next: 'grade5-3' },
  { id: 'grade5-3', speaker: 'Дмит', text: 'Пятёрку.', left: 'Дмит', right: 'Татьяна', next: 'grade5-4' },
  { id: 'grade5-4', speaker: 'Рассказчик', text: 'Татьяна обнимает Дмита так резко, будто пятёрка автоматически сделала его лучшим учеником школы.', left: 'Дмит', right: 'Татьяна', next: 'grade5-5' },
  { id: 'grade5-5', speaker: 'Дмит', text: 'Мам, задушишь!', left: 'Дмит', right: 'Татьяна', leftEmotion: 'surprised', next: 'grade5-6' },
  { id: 'grade5-6', speaker: 'Татьяна', text: 'Я знала! Я всегда знала, что ты у меня умный!', left: 'Дмит', right: 'Татьяна', rightEmotion: 'happy', next: 'grade5-7' },
  { id: 'grade5-7', speaker: 'Игорь', text: 'Один правильный ответ иногда решает всё. Но чаще нужно много правильных ответов.', left: 'Дмит', right: 'Игорь', next: 'grade5-8' },
  { id: 'grade5-8', speaker: 'Дмит', text: 'Блин.', left: 'Дмит', right: 'Игорь', next: 'grade5-9' },
  { id: 'grade5-9', speaker: 'Татьяна', text: 'Сегодня никаких «блин». Сегодня праздник!', left: 'Дмит', right: 'Татьяна', rightEmotion: 'happy', next: 'grade5-10' },
  { id: 'grade5-10', speaker: 'Игорь', text: 'За честность и результат — уважаю.', left: 'Дмит', right: 'Игорь', next: 'grade5-11' },
  { id: 'grade5-11', speaker: 'Дмит', text: 'Мне самому странно.', left: 'Дмит', right: 'Игорь', next: 'grade5-12' },
  { id: 'grade5-12', speaker: 'Игорь', text: 'Запомни это чувство. Когда побеждаешь честно, спишь спокойно.', left: 'Дмит', right: 'Игорь', next: 'cleanup-start' },

  { id: 'cleanup-start', speaker: 'Татьяна', text: 'Диня, раз уж ты дома, у меня к тебе просьба.', left: 'Дмит', right: 'Татьяна', background: 'dmit-room', next: 'cleanup-2' },
  { id: 'cleanup-2', speaker: 'Дмит', text: 'Какая?', left: 'Дмит', right: 'Татьяна', next: 'cleanup-3' },
  { id: 'cleanup-3', speaker: 'Татьяна', text: 'Уберись, пожалуйста, в своей комнате.', left: 'Дмит', right: 'Татьяна', next: 'cleanup-4' },
  { id: 'cleanup-4', speaker: 'Дмит', text: 'Я недавно убирался.', left: 'Дмит', right: 'Татьяна', next: 'cleanup-5' },
  { id: 'cleanup-5', speaker: 'Татьяна', text: 'Когда?', left: 'Дмит', right: 'Татьяна', next: 'cleanup-6' },
  { id: 'cleanup-6', speaker: 'Дмит', text: 'Ну… недавно.', left: 'Дмит', right: 'Татьяна', leftEmotion: 'thinking', next: 'cleanup-7' },
  { id: 'cleanup-7', speaker: 'Татьяна', text: 'В феврале?', left: 'Дмит', right: 'Татьяна', next: 'cleanup-8' },
  { id: 'cleanup-8', speaker: 'Дмит', text: 'Может.', left: 'Дмит', right: 'Татьяна', next: 'cleanup-9' },
  { id: 'cleanup-9', speaker: 'Татьяна', text: 'Сейчас май.', left: 'Дмит', right: 'Татьяна', rightEmotion: 'angry', next: 'cleanup-10' },
  { id: 'cleanup-10', speaker: 'Дмит', text: 'Ну и чё? Три месяца всего.', left: 'Дмит', right: 'Татьяна', next: 'cleanup-11' },
  { id: 'cleanup-11', speaker: 'Татьяна', text: 'Мне сегодня показалось, что у тебя под кроватью бегал таракан.', left: 'Дмит', right: 'Татьяна', next: 'cleanup-12' },
  { id: 'cleanup-12', speaker: 'Дмит', text: 'Это не таракан.', left: 'Дмит', right: 'Татьяна', next: 'cleanup-13' },
  { id: 'cleanup-13', speaker: 'Татьяна', text: 'А кто?', left: 'Дмит', right: 'Татьяна', next: 'cleanup-14' },
  { id: 'cleanup-14', speaker: 'Дмит', text: 'Не знаю. Может, жук.', left: 'Дмит', right: 'Татьяна', next: 'cleanup-15' },
  { id: 'cleanup-15', speaker: 'Татьяна', text: 'Он утащил кусок печенья.', left: 'Дмит', right: 'Татьяна', rightEmotion: 'surprised', next: 'cleanup-16' },
  { id: 'cleanup-16', speaker: 'Дмит', text: 'Сильный жук.', left: 'Дмит', right: 'Татьяна', next: 'cleanup-17' },
  { id: 'cleanup-17', speaker: 'Игорь', text: 'Сначала убери тех, кто уже считает комнату своей.', left: 'Дмит', right: 'Игорь', next: 'cleanup-18' },
  { id: 'cleanup-18', speaker: 'Дмит', text: 'Тараканов?', left: 'Дмит', right: 'Игорь', next: 'cleanup-19' },
  { id: 'cleanup-19', speaker: 'Игорь', text: 'Конкурентов.', left: 'Дмит', right: 'Игорь', next: 'cleanup-20' },
  { id: 'cleanup-20', speaker: 'Татьяна', text: 'Игорь, это просто насекомые.', left: 'Игорь', right: 'Татьяна', next: 'cleanup-21' },
  { id: 'cleanup-21', speaker: 'Игорь', text: 'Сегодня насекомые. Завтра требуют половину квартиры.', left: 'Игорь', right: 'Татьяна', next: 'cleanup-22' },
  { id: 'cleanup-22', speaker: 'Дмит', text: 'Ладно, сейчас разберусь.', left: 'Дмит', right: 'Игорь', next: 'roach-intro' },
  {
    id: 'roach-intro',
    speaker: 'Рассказчик',
    text: 'Дмит заходит в комнату, закрывает дверь и поднимает с пола старую футболку. Из-под кровати выбегает первый таракан. Комната на секунду становится ареной, а тапок — последним аргументом власти.',
    left: 'Дмит',
    background: 'dmit-room',
    roachGame: {
      title: 'Зачистка под диваном',
      description: 'Тараканы выскакивают из тени и быстро прячутся обратно. Бей точно: промах по полу считается побегом, а к концу они наглеют и ускоряются.',
      durationSeconds: 24,
      targetKills: 14,
      maxEscaped: 6,
      successNext: 0,
      failNext: 0,
      successEffects: { money: 500, experience: 20, flags: ['CHAPTER_1_ROOM_CLEANED', 'CHAPTER_1_ROACH_REWARD'] },
      failEffects: { experience: 6, flags: ['CHAPTER_1_ROACHES_SURVIVED'] },
    },
  },

  { id: 'roach-good-1', speaker: 'Рассказчик', text: 'Через несколько минут последний таракан падает под точным ударом тапка. Комната выглядит почти чистой, а пол впервые за долгое время становится виден.', left: 'Дмит', background: 'dmit-room', next: 'roach-good-2' },
  { id: 'roach-good-2', speaker: 'Дмит', text: 'Всё. Территория наша.', left: 'Дмит', leftEmotion: 'happy', next: 'roach-good-3' },
  { id: 'roach-good-3', speaker: 'Игорь', text: 'Закончил?', left: 'Дмит', right: 'Игорь', next: 'roach-good-4' },
  { id: 'roach-good-4', speaker: 'Дмит', text: 'Да.', left: 'Дмит', right: 'Игорь', next: 'roach-good-5' },
  { id: 'roach-good-5', speaker: 'Рассказчик', text: 'Игорь и Татьяна заходят в комнату. Они смотрят на пол с таким удивлением, будто в квартире внезапно открыли новую комнату.', left: 'Игорь', right: 'Татьяна', next: 'roach-good-6' },
  { id: 'roach-good-6', speaker: 'Татьяна', text: 'Ой, как чисто! И даже кровать заправил!', left: 'Дмит', right: 'Татьяна', rightEmotion: 'happy', next: 'roach-good-7' },
  { id: 'roach-good-7', speaker: 'Дмит', text: 'Там таракан спрятался. Пришлось.', left: 'Дмит', right: 'Татьяна', next: 'roach-good-8' },
  { id: 'roach-good-8', speaker: 'Игорь', text: 'Сколько было?', left: 'Дмит', right: 'Игорь', next: 'roach-good-9' },
  { id: 'roach-good-9', speaker: 'Дмит', text: 'Штук пятнадцать.', left: 'Дмит', right: 'Игорь', next: 'roach-good-10' },
  { id: 'roach-good-10', speaker: 'Татьяна', text: 'Пятнадцать?!', left: 'Дмит', right: 'Татьяна', rightEmotion: 'surprised', next: 'roach-good-11' },
  { id: 'roach-good-11', speaker: 'Дмит', text: 'Может, четыре. Они быстро бегали.', left: 'Дмит', right: 'Татьяна', next: 'roach-good-12' },
  { id: 'roach-good-12', speaker: 'Игорь', text: 'Главное, что зачистил. Работа выполнена хорошо.', left: 'Дмит', right: 'Игорь', next: 'roach-good-13' },
  { id: 'roach-good-13', speaker: 'Рассказчик', text: 'Игорь достаёт из кармана пятьсот рублей и протягивает Дмиту.', left: 'Дмит', right: 'Игорь', next: 'roach-good-14' },
  { id: 'roach-good-14', speaker: 'Дмит', text: 'Это мне? Пятьсот?', left: 'Дмит', right: 'Игорь', leftEmotion: 'surprised', next: 'roach-good-15' },
  { id: 'roach-good-15', speaker: 'Игорь', text: 'За результат. Умей хорошо работать — будешь хорошо получать.', left: 'Дмит', right: 'Игорь', next: 'roach-good-16' },
  { id: 'roach-good-16', speaker: 'Дмит', text: 'А можно я каждый день буду тараканов убивать?', left: 'Дмит', right: 'Татьяна', leftEmotion: 'happy', next: 'roach-good-17' },
  { id: 'roach-good-17', speaker: 'Татьяна', text: 'Нет!', left: 'Дмит', right: 'Татьяна', rightEmotion: 'angry', next: 'camp-start' },

  { id: 'roach-bad-1', speaker: 'Рассказчик', text: 'Через несколько минут Дмит устаёт бегать за тараканами. Часть скрывается под шкафом, а один особенно наглый остаётся сидеть на стене, как арендодатель.', left: 'Дмит', background: 'dmit-room', next: 'roach-bad-2' },
  { id: 'roach-bad-2', speaker: 'Дмит', text: 'Да и хуй с вами.', left: 'Дмит', leftEmotion: 'sad', next: 'roach-bad-3' },
  { id: 'roach-bad-3', speaker: 'Рассказчик', text: 'Дмит бросает тапок на пол, сгребает мусор под кровать и ложится отдыхать. Уборка официально переходит в жанр имитации.', left: 'Дмит', next: 'roach-bad-4' },
  { id: 'roach-bad-4', speaker: 'Дмит', text: 'Нормально. Стало чуть чище.', left: 'Дмит', next: 'roach-bad-5' },
  { id: 'roach-bad-5', speaker: 'Рассказчик', text: 'Из-под кровати появляется таракан и утаскивает крошку печенья.', left: 'Дмит', next: 'roach-bad-6' },
  { id: 'roach-bad-6', speaker: 'Дмит', text: 'Только тихо там.', left: 'Дмит', leftEmotion: 'thinking', next: 'camp-start' },

  { id: 'camp-start', speaker: 'Рассказчик', text: 'Дмит лежит на кровати и смотрит в потолок. Через несколько минут в комнату заглядывает Татьяна. В руках у неё сложенный лист бумаги.', left: 'Дмит', right: 'Татьяна', background: 'dmit-room', next: 'camp-2' },
  { id: 'camp-2', speaker: 'Татьяна', text: 'Диня, ты не спишь?', left: 'Дмит', right: 'Татьяна', next: 'camp-3' },
  { id: 'camp-3', speaker: 'Дмит', text: 'Не.', left: 'Дмит', right: 'Татьяна', next: 'camp-4' },
  { id: 'camp-4', speaker: 'Татьяна', text: 'У меня для тебя кое-что есть.', left: 'Дмит', right: 'Татьяна', next: 'camp-5' },
  { id: 'camp-5', speaker: 'Дмит', text: 'Если это список дел, я сплю.', left: 'Дмит', right: 'Татьяна', next: 'camp-6' },
  { id: 'camp-6', speaker: 'Татьяна', text: 'Не список.', left: 'Дмит', right: 'Татьяна', next: 'camp-7' },
  { id: 'camp-7', speaker: 'Рассказчик', text: 'Татьяна подходит к столу и кладёт перед Дмитом путёвку.', left: 'Дмит', right: 'Татьяна', next: 'camp-8' },
  { id: 'camp-8', speaker: 'Дмит', text: 'Чё это?', left: 'Дмит', right: 'Татьяна', leftEmotion: 'thinking', next: 'camp-9' },
  { id: 'camp-9', speaker: 'Татьяна', text: 'Летний оздоровительный лагерь «Строитель». На лето.', left: 'Дмит', right: 'Татьяна', next: 'camp-10' },
  { id: 'camp-10', speaker: 'Дмит', text: 'Я поеду?', left: 'Дмит', right: 'Татьяна', leftEmotion: 'surprised', next: 'camp-11' },
  { id: 'camp-11', speaker: 'Татьяна', text: 'Конечно. Свежий воздух, режим, спорт, нормальное питание.', left: 'Дмит', right: 'Татьяна', next: 'camp-12' },
  { id: 'camp-12', speaker: 'Дмит', text: 'А друзья?', left: 'Дмит', right: 'Татьяна', next: 'camp-13' },
  { id: 'camp-13', speaker: 'Татьяна', text: 'Кажется, многие из вашей школы тоже едут.', left: 'Дмит', right: 'Татьяна', next: 'camp-14' },
  { id: 'camp-14', speaker: 'Дмит', text: 'Мишган поедет?', left: 'Дмит', right: 'Татьяна', next: 'camp-15' },
  { id: 'camp-15', speaker: 'Татьяна', text: 'Не знаю. Спросишь у него.', left: 'Дмит', right: 'Татьяна', next: 'camp-16' },
  { id: 'camp-16', speaker: 'Дмит', text: 'Там дискотеки будут?', left: 'Дмит', right: 'Татьяна', leftEmotion: 'happy', next: 'camp-17' },
  { id: 'camp-17', speaker: 'Татьяна', text: 'Наверное.', left: 'Дмит', right: 'Татьяна', next: 'camp-18' },
  { id: 'camp-18', speaker: 'Дмит', text: 'И девчонки?', left: 'Дмит', right: 'Татьяна', next: 'camp-19' },
  { id: 'camp-19', speaker: 'Татьяна', text: 'Диня!', left: 'Дмит', right: 'Татьяна', rightEmotion: 'surprised', next: 'camp-20' },
  { id: 'camp-20', speaker: 'Дмит', text: 'Да просто спросил.', left: 'Дмит', right: 'Татьяна', next: 'camp-21' },
  { id: 'camp-21', speaker: 'Татьяна', text: 'Главное — веди себя прилично.', left: 'Дмит', right: 'Татьяна', next: 'camp-22' },
  { id: 'camp-22', speaker: 'Дмит', text: 'Мам, я всегда нормально себя веду.', left: 'Дмит', right: 'Татьяна', next: 'camp-23' },
  { id: 'camp-23', speaker: 'Татьяна', text: 'Сегодня тебя либо директор задержал, либо ты сам убежал из школы.', left: 'Дмит', right: 'Татьяна', next: 'camp-24' },
  { id: 'camp-24', speaker: 'Дмит', text: 'Ну сегодня день такой.', left: 'Дмит', right: 'Татьяна', next: 'camp-25' },
  { id: 'camp-25', speaker: 'Татьяна', text: 'Я хочу, чтобы ты хорошо отдохнул.', left: 'Дмит', right: 'Татьяна', rightEmotion: 'happy', next: 'camp-26' },
  { id: 'camp-26', speaker: 'Дмит', text: 'Спасибо, мам.', left: 'Дмит', right: 'Татьяна', next: 'camp-chat-intro' },
  { id: 'camp-chat-intro', speaker: 'Рассказчик', text: 'Татьяна улыбается и выходит из комнаты. Дмит сразу хватает телефон и открывает общую беседу «Арбековские».', left: 'Дмит', background: 'dmit-room', sound: 'phone-vibrate', next: 'chat-1' },

  { id: 'chat-1', ...groupMessage('Дмит', 'Пацаны.', 'outgoing', 'chat-2') },
  { id: 'chat-2', ...groupMessage('Кед', 'Живой?', 'incoming', 'chat-3') },
  { id: 'chat-3', ...groupMessage('Данз', 'Если пишет, значит руки работают.', 'incoming', 'chat-4') },
  { id: 'chat-4', ...groupMessage('Кед', 'Данз, прошло три секунды, а ты уже какую-то херню сказал.', 'incoming', 'chat-5') },
  { id: 'chat-5', ...groupMessage('Данз', 'Я стабилен.', 'incoming', 'chat-6') },
  { id: 'chat-6', ...groupMessage('Дмит', 'Мне путёвку дали в лагерь «Строитель».', 'outgoing', 'chat-7') },
  { id: 'chat-7', ...groupMessage('Кед', 'Опа.', 'incoming', 'chat-8') },
  { id: 'chat-8', ...groupMessage('Данз', 'Название мощное. Будете там кирпичи класть?', 'incoming', 'chat-9') },
  { id: 'chat-9', ...groupMessage('Дмит', 'Не знаю. Лагерь обычный.', 'outgoing', 'chat-10') },
  { id: 'chat-10', ...groupMessage('Кед', 'Я тоже туда еду.', 'incoming', 'chat-11') },
  { id: 'chat-11', ...groupMessage('Дмит', 'Серьёзно?', 'outgoing', 'chat-12') },
  { id: 'chat-12', ...groupMessage('Кед', 'Да. Мать сказала, там кормят пять раз в день.', 'incoming', 'chat-13') },
  { id: 'chat-13', ...groupMessage('Дмит', 'Тебе только это и надо.', 'outgoing', 'chat-14') },
  { id: 'chat-14', ...groupMessage('Кед', 'А что ещё человеку надо? Гречка, мясо и уважение.', 'incoming', 'chat-15') },
  { id: 'chat-15', ...groupMessage('Данз', 'А девчонки?', 'incoming', 'chat-16') },
  { id: 'chat-16', ...groupMessage('Кед', 'Тебе они зачем? Ты с живыми людьми разговаривать не умеешь.', 'incoming', 'chat-17') },
  { id: 'chat-17', ...groupMessage('Данз', 'На сервере нормально разговариваю.', 'incoming', 'chat-18') },
  { id: 'chat-18', ...groupMessage('Дмит', 'Ты там таксистом работаешь.', 'outgoing', 'chat-19') },
  { id: 'chat-19', ...groupMessage('Данз', 'Уважаемая профессия. Я уже заместитель старшего водителя.', 'incoming', 'chat-20') },
  { id: 'chat-20', ...groupMessage('Кед', 'Заместитель водителя — это пассажир?', 'incoming', 'chat-21') },
  { id: 'chat-21', ...groupMessage('Дмит', 'Ха-ха.', 'outgoing', 'chat-22') },
  { id: 'chat-22', ...groupMessage('Данз', 'Смешно вам. Зато у меня машина есть.', 'incoming', 'chat-23') },
  { id: 'chat-23', ...groupMessage('Кед', 'В игре.', 'incoming', 'chat-24') },
  { id: 'chat-24', ...groupMessage('Данз', 'В игре у меня и девушка есть. Правда, это может быть мужик.', 'incoming', 'chat-25') },
  { id: 'chat-25', ...groupMessage('Кед', 'Скорее всего, это мужик.', 'incoming', 'chat-26') },
  { id: 'chat-26', ...groupMessage('Данз', 'Любви возраст и голос не помеха.', 'incoming', 'chat-27') },
  { id: 'chat-27', ...groupMessage('Дмит', 'Фу, бля.', 'outgoing', 'chat-28') },
  { id: 'chat-28', ...groupMessage('Кед', 'Короче, сегодня выходите?', 'incoming', 'chat-29') },
  { id: 'chat-29', ...groupMessage('Дмит', 'Куда?', 'outgoing', 'chat-30') },
  { id: 'chat-30', ...groupMessage('Кед', 'На наше место. Посидим перед лагерем.', 'incoming', 'chat-31') },
  { id: 'chat-31', ...groupMessage('Данз', 'Я уже готов.', 'incoming', 'chat-32') },
  { id: 'chat-32', ...groupMessage('Дмит', 'Ты всегда готов. Только денег у тебя никогда нет.', 'outgoing', 'chat-33') },
  { id: 'chat-33', ...groupMessage('Данз', 'Деньги портят людей.', 'incoming', 'chat-34') },
  { id: 'chat-34', ...groupMessage('Кед', 'Особенно когда их нет.', 'incoming', 'chat-35') },
  { id: 'chat-35', ...groupMessage('Дмит', 'Во сколько?', 'outgoing', 'chat-36') },
  { id: 'chat-36', ...groupMessage('Кед', 'Часов в восемь.', 'incoming', 'chat-37') },
  { id: 'chat-37', ...groupMessage('Данз', 'Надо взять что-нибудь.', 'incoming', 'chat-38') },
  { id: 'chat-38', ...groupMessage('Дмит', 'Пожрать?', 'outgoing', 'chat-39') },
  { id: 'chat-39', ...groupMessage('Кед', 'Пожрать я возьму.', 'incoming', 'chat-40') },
  { id: 'chat-40', ...groupMessage('Данз', 'Выпить.', 'incoming', 'chat-choice') },
  {
    id: 'chat-choice',
    speaker: 'Кед',
    text: 'Дмит, выбирай. У тебя сегодня ответственная должность.',
    background: 'dmit-room',
    phoneMessage: { contact: 'Арбековские', direction: 'incoming' },
    choices: [
      { label: 'Берём водку и пиво. Гулять так гулять. — 500 ₽', next: returnHomeQuestStartScene, requiresMoney: 500, effects: { money: -500, experience: 8, flags: ['CHAPTER_1_ALCOHOL_HEAVY'] } },
      { label: 'Возьмём только «Охоту Крепкую». — 150 ₽', next: returnHomeQuestStartScene, requiresMoney: 150, effects: { money: -150, experience: 5, flags: ['CHAPTER_1_ALCOHOL_BEER'] } },
      { label: 'Я пить не буду. Просто посижу с вами. — бесплатно', next: returnHomeQuestStartScene, effects: { experience: 7, flags: ['CHAPTER_1_ALCOHOL_SOBER'] } },
    ],
  },

  { id: 'vodka-1', ...groupMessage('Дмит', 'Берём водку и пиво. Гулять так гулять.', 'outgoing', 'vodka-2') },
  { id: 'vodka-2', ...groupMessage('Кед', 'Ты смешивать собрался?', 'incoming', 'vodka-3') },
  { id: 'vodka-3', ...groupMessage('Дмит', 'А чё?', 'outgoing', 'vodka-4') },
  { id: 'vodka-4', ...groupMessage('Кед', 'Батя говорил, смешивать нельзя.', 'incoming', 'vodka-5') },
  { id: 'vodka-5', ...groupMessage('Данз', 'Мой организм всё переработает.', 'incoming', 'vodka-6') },
  { id: 'vodka-6', ...groupMessage('Кед', 'Твой организм от школьной котлеты два дня восстанавливался.', 'incoming', 'vodka-7') },
  { id: 'vodka-7', ...groupMessage('Данз', 'Это была плохая котлета.', 'incoming', 'vodka-8') },
  { id: 'vodka-8', ...groupMessage('Дмит', 'Короче, возьмём понемногу.', 'outgoing', 'vodka-9') },
  { id: 'vodka-9', ...groupMessage('Кед', 'У тебя деньги есть?', 'incoming', 'vodka-10') },
  { id: 'vodka-10', ...groupMessage('Дмит', 'Есть. Мне батя пятьсот дал.', 'outgoing', 'vodka-11') },
  { id: 'vodka-11', ...groupMessage('Кед', 'За что?', 'incoming', 'vodka-12') },
  { id: 'vodka-12', ...groupMessage('Дмит', 'Тараканов убил.', 'outgoing', 'vodka-13') },
  { id: 'vodka-13', ...groupMessage('Данз', 'Наёмный убийца.', 'incoming', 'vodka-14') },
  { id: 'vodka-14', ...groupMessage('Кед', 'Не трать всё. В лагере пригодится.', 'incoming', 'vodka-15') },
  { id: 'vodka-15', ...groupMessage('Дмит', 'Да разберусь. В восемь тогда.', 'outgoing', 'after-alcohol-route') },

  { id: 'beer-1', ...groupMessage('Дмит', 'Возьмём только «Охоту Крепкую».', 'outgoing', 'beer-2') },
  { id: 'beer-2', ...groupMessage('Кед', 'Вот это по-нашему.', 'incoming', 'beer-3') },
  { id: 'beer-3', ...groupMessage('Данз', 'Сколько?', 'incoming', 'beer-4') },
  { id: 'beer-4', ...groupMessage('Дмит', 'Каждому по одной.', 'outgoing', 'beer-5') },
  { id: 'beer-5', ...groupMessage('Данз', 'Мне две.', 'incoming', 'beer-6') },
  { id: 'beer-6', ...groupMessage('Кед', 'Ты после половины банки начинаешь рассказывать, как тебя уважают в GTA.', 'incoming', 'beer-7') },
  { id: 'beer-7', ...groupMessage('Данз', 'Меня там реально уважают.', 'incoming', 'beer-8') },
  { id: 'beer-8', ...groupMessage('Дмит', 'Тебя там в прошлый раз за неправильную парковку посадили.', 'outgoing', 'beer-9') },
  { id: 'beer-9', ...groupMessage('Данз', 'Это был конфликт с властью.', 'incoming', 'beer-10') },
  { id: 'beer-10', ...groupMessage('Кед', 'Это был столб.', 'incoming', 'beer-11') },
  { id: 'beer-11', ...groupMessage('Дмит', 'Короче, по одной.', 'outgoing', 'beer-12') },
  { id: 'beer-12', ...groupMessage('Кед', 'И я еду возьму. Только не одну гречку.', 'incoming', 'beer-13') },
  { id: 'beer-13', ...groupMessage('Дмит', 'Гречка — основа вечера?', 'outgoing', 'beer-14') },
  { id: 'beer-14', ...groupMessage('Кед', 'Гречка — основа мира.', 'incoming', 'beer-15') },
  { id: 'beer-15', ...groupMessage('Данз', 'А девушки?', 'incoming', 'beer-16') },
  { id: 'beer-16', ...groupMessage('Дмит', 'Тебе и девушки не отвечают.', 'outgoing', 'beer-17') },
  { id: 'beer-17', ...groupMessage('Кед', 'Ха-ха!', 'incoming', 'beer-18') },
  { id: 'beer-18', ...groupMessage('Дмит', 'В восемь на месте.', 'outgoing', 'after-alcohol-route') },

  { id: 'sober-1', ...groupMessage('Дмит', 'Я пить не буду. Просто посижу с вами.', 'outgoing', 'sober-2') },
  { id: 'sober-2', ...groupMessage('Кед', 'С чего вдруг?', 'incoming', 'sober-3') },
  { id: 'sober-3', ...groupMessage('Дмит', 'Да не хочу.', 'outgoing', 'sober-4') },
  { id: 'sober-4', ...groupMessage('Данз', 'Тебя подменили?', 'incoming', 'sober-5') },
  { id: 'sober-5', ...groupMessage('Дмит', 'Нет.', 'outgoing', 'sober-6') },
  { id: 'sober-6', ...groupMessage('Кед', 'Может, родители дома?', 'incoming', 'sober-7') },
  { id: 'sober-7', ...groupMessage('Дмит', 'При чём тут родители? Просто не буду.', 'outgoing', 'sober-8') },
  { id: 'sober-8', ...groupMessage('Данз', 'Правильно. Будешь нашим водителем.', 'incoming', 'sober-9') },
  { id: 'sober-9', ...groupMessage('Дмит', 'На чём?', 'outgoing', 'sober-10') },
  { id: 'sober-10', ...groupMessage('Данз', 'Не знаю. На велосипеде.', 'incoming', 'sober-11') },
  { id: 'sober-11', ...groupMessage('Кед', 'Втроём на велосипеде?', 'incoming', 'sober-12') },
  { id: 'sober-12', ...groupMessage('Данз', 'Я сяду на раму.', 'incoming', 'sober-13') },
  { id: 'sober-13', ...groupMessage('Дмит', 'Ты сядешь в кусты.', 'outgoing', 'sober-14') },
  { id: 'sober-14', ...groupMessage('Кед', 'Да не давите на него. Не хочет — и нормально.', 'incoming', 'sober-15') },
  { id: 'sober-15', ...groupMessage('Дмит', 'Во. Кед понимает.', 'outgoing', 'sober-16') },
  { id: 'sober-16', ...groupMessage('Кед', 'Больше нам останется.', 'incoming', 'sober-17') },
  { id: 'sober-17', ...groupMessage('Дмит', 'А вот теперь понятно.', 'outgoing', 'sober-18') },
  { id: 'sober-18', ...groupMessage('Кед', 'Тогда бери сок или газировку. И приходи всё равно.', 'incoming', 'sober-19') },
  { id: 'sober-19', ...groupMessage('Дмит', 'Ладно. В восемь буду.', 'outgoing', 'after-alcohol-route') },

  {
    id: 'after-alcohol-route',
    speaker: 'Рассказчик',
    text: 'Выбор зафиксирован. Вечер уже где-то рядом, шуршит пакетами, комарами и будущими плохими решениями.',
    background: 'dmit-room',
    nextByFlag: [{ flag: 'CHAPTER_1_LEFT_MISHGAN', next: 'mishgan-silent-1' }],
    fallbackNext: 'quest-end',
  },
  { id: 'mishgan-silent-1', speaker: 'Рассказчик', text: 'Мишган появляется в списке участников беседы. Он читает сообщения, но ничего не пишет.', background: 'dmit-room', phoneMessage: { contact: 'Арбековские', direction: 'incoming' }, next: 'mishgan-silent-2' },
  { id: 'mishgan-silent-2', ...groupMessage('Кед', 'А Мишган чё молчит?', 'incoming', 'mishgan-silent-3') },
  { id: 'mishgan-silent-3', ...groupMessage('Дмит', 'Да хрен его знает.', 'outgoing', 'mishgan-silent-4') },
  { id: 'mishgan-silent-4', ...groupMessage('Кед', 'Вы же вместе были.', 'incoming', 'mishgan-silent-5') },
  { id: 'mishgan-silent-5', ...groupMessage('Дмит', 'Потом расскажу.', 'outgoing', 'mishgan-silent-6') },
  { id: 'mishgan-silent-6', ...groupMessage('Данз', 'Может, у него руки после бокса устали.', 'incoming', 'mishgan-silent-7') },
  { id: 'mishgan-silent-7', ...groupMessage('Кед', 'Лучше бы у тебя руки иногда уставали.', 'incoming', 'mishgan-silent-8') },
  { id: 'mishgan-silent-8', ...groupMessage('Дмит', 'Фу, бля. Я вышел.', 'outgoing', 'quest-end') },

  {
    id: 'quest-end',
    speaker: 'Рассказчик',
    text: 'Квест «Возвращение домой» завершён. Дмит закрывает телефон, а квартира снова становится тихой — слишком тихой для человека, который только что выбрал себе вечер.',
    left: 'Дмит',
    background: 'dmit-room',
    sound: 'quest-complete',
    effects: { flags: ['CHAPTER_1_RETURNED_HOME'], experience: 12 },
  },
])

const roachIntro = returnHomeQuestScenes.find((scene) => scene.roachGame)?.roachGame
if (roachIntro) {
  roachIntro.successNext = returnHomeQuestScenes.findIndex((scene) => scene.text.startsWith('Через несколько минут последний таракан')) + returnHomeQuestStartScene
  roachIntro.failNext = returnHomeQuestScenes.findIndex((scene) => scene.text.startsWith('Через несколько минут Дмит устаёт')) + returnHomeQuestStartScene
}

const gradesChoice = returnHomeQuestScenes.find((scene) => scene.choices?.some((choice) => choice.label.includes('Да нормально')))
if (gradesChoice?.choices) {
  gradesChoice.choices[0].next = returnHomeQuestScenes.findIndex((scene) => scene.text === 'Да нормально всё. Ничего не ставили.') + returnHomeQuestStartScene
  gradesChoice.choices[0].failNext = returnHomeQuestScenes.findIndex((scene) => scene.text === 'Отвечай прямо.') + returnHomeQuestStartScene
  gradesChoice.choices[1].next = returnHomeQuestScenes.findIndex((scene) => scene.text === 'Отвечай прямо.') + returnHomeQuestStartScene
}

const alcoholChoice = returnHomeQuestScenes.find((scene) => scene.choices?.some((choice) => choice.label.includes('500 ₽')))
if (alcoholChoice?.choices) {
  alcoholChoice.choices[0].next = returnHomeQuestScenes.findIndex((scene) => scene.text === 'Берём водку и пиво. Гулять так гулять.') + returnHomeQuestStartScene
  alcoholChoice.choices[1].next = returnHomeQuestScenes.findIndex((scene) => scene.text === 'Возьмём только «Охоту Крепкую».') + returnHomeQuestStartScene
  alcoholChoice.choices[2].next = returnHomeQuestScenes.findIndex((scene) => scene.text === 'Я пить не буду. Просто посижу с вами.') + returnHomeQuestStartScene
}
