import type { Scene } from '../../../../types/story'

// ????? 56-183. ??????? ? ???????? ????? ????????? ? ????? ? ????? ? ?????.
export const meetMishganQuestScenes: Scene[] = [
  {
      speaker: "Рассказчик",
      text: "У кабинета географии Дмит ловит воздух так, будто только что вышел не с урока, а из районного суда. Мишган уже ждёт у стены и оценивает лицо друга как табло после боя.",
      left: "Дмит",
      right: "Мишган",
      background: "school",
      nextByFlag: [
        { flag: "control-work-caught", next: 57 },
        { flag: "geography-grade-5", next: 84 },
        { flag: "geography-grade-4", next: 75 },
        { flag: "geography-grade-3", next: 66 },
        { flag: "geography-grade-2", next: 57 },
      ],
      fallbackNext: 57,
    },
  {
      speaker: "Мишган",
      text: "Ну чё, чемпион географии, как бой прошёл?",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "thinking",
      next: 58,
    },
  {
      speaker: "Дмит",
      text: "Два поставила, сука.",
      left: "Дмит",
      right: "Мишган",
      leftEmotion: "sad",
      rightEmotion: "surprised",
      next: 59,
    },
  {
      speaker: "Мишган",
      text: "Уф-уф, бля. Это не двойка. Это два точных удара по твоему дневнику.",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "sad",
      next: 60,
    },
  {
      speaker: "Дмит",
      text: "Мать мне потом третий пробьёт.",
      left: "Дмит",
      right: "Мишган",
      leftEmotion: "sad",
      next: 61,
    },
  {
      speaker: "Мишган",
      text: "Главное — не опускай руки. И дневник ей не показывай.",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "happy",
      next: 62,
    },
  {
      speaker: "Дмит",
      text: "Охуенный совет.",
      left: "Дмит",
      right: "Мишган",
      next: 63,
    },
  {
      speaker: "Мишган",
      text: "Я плохого не посоветую. Я боксёр.",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "happy",
      next: 64,
    },
  {
      speaker: "Дмит",
      text: "Ты по географии тоже два получил.",
      left: "Дмит",
      right: "Мишган",
      next: 65,
    },
  {
      speaker: "Мишган",
      text: "Потому что она спросила, где Куба. Я сказал — в левом углу ринга.",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "thinking",
      next: 93,
    },
  {
      speaker: "Мишган",
      text: "Ну чё, сколько тебе эта психованная поставила?",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "thinking",
      next: 67,
    },
  {
      speaker: "Дмит",
      text: "Три.",
      left: "Дмит",
      right: "Мишган",
      next: 68,
    },
  {
      speaker: "Мишган",
      text: "Уф-уф! Победа по очкам, бля!",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "happy",
      next: 69,
    },
  {
      speaker: "Дмит",
      text: "Какая победа? Я половину у Кеда списал.",
      left: "Дмит",
      right: "Мишган",
      leftEmotion: "thinking",
      next: 70,
    },
  {
      speaker: "Мишган",
      text: "Неважно, как победил. Главное — судья руку поднял.",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "happy",
      next: 71,
    },
  {
      speaker: "Дмит",
      text: "Она мне дневником по башке дала.",
      left: "Дмит",
      right: "Мишган",
      next: 72,
    },
  {
      speaker: "Мишган",
      text: "Значит, бой был контактный.",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "thinking",
      next: 73,
    },
  {
      speaker: "Дмит",
      text: "Пошли уже. Заебала школа.",
      left: "Дмит",
      right: "Мишган",
      next: 74,
    },
  {
      speaker: "Мишган",
      text: "Поддерживаю. Уходим красиво, как чемпионы. Только тихо. Тихо, как удар в печень.",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "happy",
      next: 93,
    },
  {
      speaker: "Мишган",
      text: "Дмит, колись. Чё поставили?",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "thinking",
      next: 76,
    },
  {
      speaker: "Дмит",
      text: "Четыре.",
      left: "Дмит",
      right: "Мишган",
      leftEmotion: "happy",
      next: 77,
    },
  {
      speaker: "Мишган",
      text: "ЧЕГ—",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "surprised",
      next: 78,
    },
  {
      speaker: "Дмит",
      text: "Тихо ты, дебил!",
      left: "Дмит",
      right: "Мишган",
      next: 79,
    },
  {
      speaker: "Мишган",
      text: "Уф-уф, бля! Четыре — это почти чемпионский пояс!",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "happy",
      next: 80,
    },
  {
      speaker: "Дмит",
      text: "Я сам охуел.",
      left: "Дмит",
      right: "Мишган",
      leftEmotion: "surprised",
      next: 81,
    },
  {
      speaker: "Мишган",
      text: "Ты готовился?",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "thinking",
      next: 82,
    },
  {
      speaker: "Дмит",
      text: "Нет. Она просто перепутала меня с другим.",
      left: "Дмит",
      right: "Мишган",
      next: 83,
    },
  {
      speaker: "Мишган",
      text: "Победителей не судят. Пока она не поняла — валим непобеждёнными.",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "happy",
      next: 93,
    },
  {
      speaker: "Мишган",
      text: "Ну чё там?",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "thinking",
      next: 85,
    },
  {
      speaker: "Дмит",
      text: "Пять.",
      left: "Дмит",
      right: "Мишган",
      leftEmotion: "happy",
      next: 86,
    },
  {
      speaker: "Мишган",
      text: "Чё?",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "surprised",
      next: 87,
    },
  {
      speaker: "Дмит",
      text: "Пять поставила.",
      left: "Дмит",
      right: "Мишган",
      leftEmotion: "happy",
      next: 88,
    },
  {
      speaker: "Мишган",
      text: "Уф… уф… БЛЯ! ДМИТ — ЧЕМПИОН МИРА ПО ГЕОГРАФИИ!",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "happy",
      next: 89,
    },
  {
      speaker: "Дмит",
      text: "Да заткнись ты!",
      left: "Дмит",
      right: "Мишган",
      next: 90,
    },
  {
      speaker: "Мишган",
      text: "Как ты это сделал? Нокаутировал её глобусом?",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "surprised",
      next: 91,
    },
  {
      speaker: "Дмит",
      text: "Ответил на вопрос. Сам. Без подсказки.",
      left: "Дмит",
      right: "Мишган",
      leftEmotion: "thinking",
      next: 92,
    },
  {
      speaker: "Мишган",
      text: "Бля, не верю. Покажи дневник потом. Сейчас валим, пока она пятёрку обратно не забрала.",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "happy",
      next: 93,
    },
  {
      speaker: "Рассказчик",
      text: "Дмит и Мишган спускаются на первый этаж. В коридоре пусто. Даже дежурная учительница куда-то исчезла, словно школа сама на минуту устала от школы.",
      left: "Дмит",
      right: "Мишган",
      background: "school",
      next: 94,
    },
  {
      speaker: "Дмит",
      text: "Чё-то тихо слишком.",
      left: "Дмит",
      right: "Мишган",
      next: 95,
    },
  {
      speaker: "Мишган",
      text: "Перед боем всегда тихо.",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "thinking",
      next: 96,
    },
  {
      speaker: "Дмит",
      text: "Какой ещё бой? Нам просто выйти надо.",
      left: "Дмит",
      right: "Мишган",
      next: 97,
    },
  {
      speaker: "Мишган",
      text: "Любой выход — это бой, бля.",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "happy",
      next: 98,
    },
  {
      speaker: "Дмит",
      text: "Не пизди и смотри, есть кто у двери.",
      left: "Дмит",
      right: "Мишган",
      next: 99,
    },
  {
      speaker: "Рассказчик",
      text: "Мишган выглядывает из-за угла. Вахта пустая. Дверь на улицу приоткрыта, и через щель видно двор — влажный, серый, но невероятно свободный.",
      left: "Дмит",
      right: "Мишган",
      next: 100,
    },
  {
      speaker: "Мишган",
      text: "Путь свободен.",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "happy",
      next: 101,
    },
  {
      speaker: "Дмит",
      text: "Точно?",
      left: "Дмит",
      right: "Мишган",
      next: 102,
    },
  {
      speaker: "Мишган",
      text: "Сто процентов. Я всё просчитал.",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "thinking",
      next: 103,
    },
  {
      speaker: "Дмит",
      text: "Ты считать не умеешь.",
      left: "Дмит",
      right: "Мишган",
      next: 104,
    },
  {
      speaker: "Мишган",
      text: "Но чувствую хорошо.",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "happy",
      next: 105,
    },
  {
      speaker: "Рассказчик",
      text: "Ребята выходят на крыльцо. Перед ними двор, калитка и долгожданная свобода — всего несколько метров асфальта, но по ощущениям целая взрослая жизнь.",
      left: "Дмит",
      right: "Мишган",
      background: "school",
      next: 106,
    },
  {
      speaker: "Дмит",
      text: "Вроде всё.",
      left: "Дмит",
      right: "Мишган",
      next: 107,
    },
  {
      speaker: "Мишган",
      text: "Не спеши. Сначала я.",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "thinking",
      next: 108,
    },
  {
      speaker: "Дмит",
      text: "С хуя ли?",
      left: "Дмит",
      right: "Мишган",
      next: 109,
    },
  {
      speaker: "Мишган",
      text: "Я приму первый удар.",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "happy",
      next: 110,
    },
  {
      speaker: "Дмит",
      text: "Какой удар, придурок?",
      left: "Дмит",
      right: "Мишган",
      next: 111,
    },
  {
      speaker: "Мишган",
      text: "Мало ли. Охранник, директор, завуч. У каждого своя весовая категория.",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "thinking",
      next: 112,
    },
  {
      speaker: "Рассказчик",
      text: "Мишган осторожно идёт к калитке. Дмит двигается следом и постоянно оглядывается на школу, как будто здание сейчас само напишет на него докладную.",
      left: "Дмит",
      right: "Мишган",
      next: 113,
    },
  {
      speaker: "Дмит",
      text: "Давай быстрее.",
      left: "Дмит",
      right: "Мишган",
      next: 114,
    },
  {
      speaker: "Мишган",
      text: "Не дави. Я работаю на ногах.",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "thinking",
      next: 115,
    },
  {
      speaker: "Дмит",
      text: "Ты просто крадёшься как дебил.",
      left: "Дмит",
      right: "Мишган",
      next: 116,
    },
  {
      speaker: "Охранник",
      text: "А НУ СТОЯТЬ!",
      left: "Мишган",
      right: "Охранник",
      rightEmotion: "angry",
      tone: "danger",
      sound: "guard-shout",
      next: 117,
    },
  {
      speaker: "Мишган",
      text: "Контакт!",
      left: "Мишган",
      right: "Охранник",
      leftEmotion: "surprised",
      tone: "danger",
      next: 118,
    },
  {
      speaker: "Дмит",
      text: "Бежим, бля!",
      left: "Дмит",
      right: "Мишган",
      leftEmotion: "surprised",
      rightEmotion: "surprised",
      tone: "danger",
      sound: "dmit-run",
      next: 119,
    },
  {
      speaker: "Рассказчик",
      text: "Из-за угла школы вылетает злой охранник. Он красный, тяжело дышит и размахивает связкой ключей так, будто это не ключи, а государственная власть.",
      left: "Мишган",
      right: "Охранник",
      tone: "danger",
      sound: "guard-run",
      next: 120,
    },
  {
      speaker: "Охранник",
      text: "КУДА ПОШЛИ?! СТОЯТЬ, СУКИ!",
      left: "Мишган",
      right: "Охранник",
      rightEmotion: "angry",
      tone: "danger",
      next: 121,
    },
  {
      speaker: "Мишган",
      text: "Уф-уф! Работаем на дистанции!",
      left: "Мишган",
      right: "Охранник",
      leftEmotion: "happy",
      tone: "danger",
      next: 122,
    },
  {
      speaker: "Дмит",
      text: "Просто беги!",
      left: "Дмит",
      right: "Мишган",
      leftEmotion: "surprised",
      tone: "danger",
      next: 123,
    },
  {
      speaker: "Охранник",
      text: "Я ВАС ВСЁ РАВНО ДОГОНЮ!",
      left: "Мишган",
      right: "Охранник",
      rightEmotion: "angry",
      tone: "danger",
      next: 124,
    },
  {
      speaker: "Мишган",
      text: "Не догонишь! У тебя ноги не поставлены!",
      left: "Мишган",
      right: "Охранник",
      leftEmotion: "happy",
      tone: "danger",
      next: 125,
    },
  {
      speaker: "Охранник",
      text: "ЧЕГО?!",
      left: "Мишган",
      right: "Охранник",
      rightEmotion: "angry",
      tone: "danger",
      next: 126,
    },
  {
      speaker: "Дмит",
      text: "Не зли его, долбоёб!",
      left: "Дмит",
      right: "Мишган",
      leftEmotion: "surprised",
      rightEmotion: "surprised",
      tone: "danger",
      next: 127,
    },
  {
      speaker: "Рассказчик",
      text: "Мишган оборачивается, чтобы показать охраннику боксёрскую стойку, цепляется ногой за бордюр и падает. Вся его тактика ложится вместе с ним.",
      left: "Мишган",
      right: "Охранник",
      tone: "danger",
      sound: "mishgan-fall",
      next: 128,
    },
  {
      speaker: "Мишган",
      text: "Бля!",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "sad",
      tone: "danger",
      next: 129,
    },
  {
      speaker: "Дмит",
      text: "Мишган!",
      left: "Дмит",
      right: "Мишган",
      leftEmotion: "surprised",
      rightEmotion: "sad",
      tone: "danger",
      next: 130,
    },
  {
      speaker: "Охранник",
      text: "ПОПАЛИСЬ!",
      left: "Мишган",
      right: "Охранник",
      rightEmotion: "angry",
      tone: "danger",
      next: 131,
    },
  {
      speaker: "Рассказчик",
      text: "До калитки остаётся несколько метров. Охранник уже близко. Мишган лежит на земле и пытается подняться, но его школьные туфли спорят с гравитацией и проигрывают.",
      left: "Дмит",
      right: "Мишган",
      tone: "danger",
      next: 132,
    },
  {
      speaker: "Мишган",
      text: "Дмит, вали! Я задержу его!",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "surprised",
      tone: "danger",
      next: 133,
    },
  {
      speaker: "Дмит",
      text: "Ты как его задержишь? Ты в луже лежишь!",
      left: "Дмит",
      right: "Мишган",
      leftEmotion: "surprised",
      tone: "danger",
      next: 134,
    },
  {
      speaker: "Мишган",
      text: "Это нижняя стойка, бля!",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "happy",
      tone: "danger",
      choices: [
        {
          label: "Да хуй с ним. Своих не бросаем.",
          next: 135,
          failNext: 160,
          requires: { strength: 5 },
          effects: {
            flags: ["CHAPTER_1_HELPED_MISHGAN"],
            experience: 25,
          },
          failureEffects: {
            flags: ["CHAPTER_1_LEFT_MISHGAN", "CHAPTER_1_FAILED_TO_LIFT_MISHGAN"],
            experience: 6,
          },
          failureText: "Дмит хватает Мишгана за рукав, тянет изо всех сил, но Мишган лежит так уверенно, будто подписал договор с землёй.",
        },
        {
          label: "Извини, братан. Я домой.",
          next: 160,
          effects: {
            flags: ["CHAPTER_1_LEFT_MISHGAN"],
            experience: 10,
          },
        },
      ],
    },
  {
      speaker: "Дмит",
      text: "Да хуй с ним. Своих не бросаем.",
      left: "Дмит",
      right: "Мишган",
      leftEmotion: "thinking",
      rightEmotion: "surprised",
      tone: "danger",
      next: 136,
    },
  {
      speaker: "Мишган",
      text: "Уф-уф, бля! Вот это командный дух!",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "happy",
      tone: "danger",
      next: 137,
    },
  {
      speaker: "Дмит",
      text: "Руку давай!",
      left: "Дмит",
      right: "Мишган",
      tone: "danger",
      next: 138,
    },
  {
      speaker: "Рассказчик",
      text: "Дмит хватает Мишгана за рукав. Ткань тянется, Мишган пыхтит, охранник приближается. На секунду это похоже на героическое спасение, если не смотреть на лужу и школьный забор.",
      left: "Дмит",
      right: "Мишган",
      tone: "danger",
      sound: "dmit-run",
      next: 139,
    },
  {
      speaker: "Дмит",
      text: "Да вставай ты, жирный!",
      left: "Дмит",
      right: "Мишган",
      leftEmotion: "surprised",
      tone: "danger",
      next: 140,
    },
  {
      speaker: "Мишган",
      text: "Это мышцы!",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "angry",
      tone: "danger",
      next: 141,
    },
  {
      speaker: "Дмит",
      text: "Мне похуй, поднимай свои мышцы!",
      left: "Дмит",
      right: "Мишган",
      tone: "danger",
      next: 142,
    },
  {
      speaker: "Охранник",
      text: "Ну всё. Набегались?",
      left: "Дмит",
      right: "Охранник",
      rightEmotion: "angry",
      tone: "danger",
      sound: "guard-run",
      next: 143,
    },
  {
      speaker: "Мишган",
      text: "Мы ещё можем договориться.",
      left: "Мишган",
      right: "Охранник",
      rightEmotion: "angry",
      tone: "danger",
      next: 144,
    },
  {
      speaker: "Охранник",
      text: "Как?",
      left: "Мишган",
      right: "Охранник",
      tone: "danger",
      next: 145,
    },
  {
      speaker: "Мишган",
      text: "Один раунд. Если я побеждаю — мы уходим.",
      left: "Мишган",
      right: "Охранник",
      leftEmotion: "thinking",
      tone: "danger",
      next: 146,
    },
  {
      speaker: "Охранник",
      text: "Ты совсем больной?",
      left: "Мишган",
      right: "Охранник",
      rightEmotion: "angry",
      tone: "danger",
      next: 147,
    },
  {
      speaker: "Дмит",
      text: "Он боксёр.",
      left: "Дмит",
      right: "Охранник",
      tone: "danger",
      next: 148,
    },
  {
      speaker: "Охранник",
      text: "Вижу. Оба к директору. Быстро.",
      left: "Дмит",
      right: "Охранник",
      rightEmotion: "angry",
      tone: "danger",
      next: 149,
    },
  {
      speaker: "Дмит",
      text: "Может, просто обратно на урок?",
      left: "Дмит",
      right: "Охранник",
      leftEmotion: "sad",
      tone: "danger",
      next: 150,
    },
  {
      speaker: "Охранник",
      text: "К директору.",
      left: "Дмит",
      right: "Охранник",
      rightEmotion: "angry",
      tone: "danger",
      next: 151,
    },
  {
      speaker: "Мишган",
      text: "А директор в какой весовой?",
      left: "Мишган",
      right: "Охранник",
      leftEmotion: "thinking",
      tone: "danger",
      next: 152,
    },
  {
      speaker: "Охранник",
      text: "Сейчас узнаешь.",
      left: "Мишган",
      right: "Охранник",
      rightEmotion: "angry",
      tone: "danger",
      next: 153,
    },
  {
      speaker: "Дмит",
      text: "Мишган, завали ебало.",
      left: "Дмит",
      right: "Мишган",
      leftEmotion: "sad",
      rightEmotion: "happy",
      tone: "danger",
      next: 154,
    },
  {
      speaker: "Рассказчик",
      text: "Охранник берёт обоих и ведёт обратно. Школьный двор остаётся позади, но в голове Дмита уже щёлкает новая зарубка: своих не бросают, даже если свои падают в лужу максимально тупо.",
      left: "Дмит",
      right: "Мишган",
      tone: "danger",
      next: 155,
    },
  {
      speaker: "Мишган",
      text: "Зато почти вышли.",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "happy",
      tone: "danger",
      next: 156,
    },
  {
      speaker: "Дмит",
      text: "Ага. Метров на десять.",
      left: "Дмит",
      right: "Мишган",
      tone: "danger",
      next: 157,
    },
  {
      speaker: "Мишган",
      text: "Главное — прогресс. А если директор будет орать — держи блок.",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "happy",
      tone: "danger",
      next: 158,
    },
  {
      speaker: "Рассказчик",
      text: "Квест Встреча с Мишганом у входа в школу завершён. Дмит получает важный урок Арбеково: иногда репутация начинается там, где здравый смысл заканчивается.",
      left: "Дмит",
      right: "Мишган",
      background: "school",
      sound: "quest-complete",
      next: 159,
    },
  {
      speaker: "Рассказчик",
      text: "Где-то далеко будущий сюжет уже открыл блокнот и сделал пометку: этот Дмит своих не бросает.",
      left: "Дмит",
      right: "Мишган",
      background: "school",
    },
  {
      speaker: "Дмит",
      text: "Извини, братан. Я домой.",
      left: "Дмит",
      right: "Мишган",
      leftEmotion: "surprised",
      rightEmotion: "surprised",
      tone: "danger",
      next: 161,
    },
  {
      speaker: "Мишган",
      text: "Чё?",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "sad",
      tone: "danger",
      next: 162,
    },
  {
      speaker: "Дмит",
      text: "Я потом объясню!",
      left: "Дмит",
      right: "Мишган",
      leftEmotion: "surprised",
      tone: "danger",
      next: 163,
    },
  {
      speaker: "Мишган",
      text: "Дмит, ты серьёзно?!",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "angry",
      tone: "danger",
      next: 164,
    },
  {
      speaker: "Рассказчик",
      text: "Дмит разворачивается и летит к калитке. Позади остаётся Мишган, охранник и тот самый неприятный звук, когда дружба впервые скрипит громче школьной двери.",
      left: "Дмит",
      right: "Мишган",
      tone: "danger",
      sound: "dmit-run",
      next: 165,
    },
  {
      speaker: "Охранник",
      text: "СТОЯТЬ!",
      left: "Дмит",
      right: "Охранник",
      rightEmotion: "angry",
      tone: "danger",
      sound: "guard-shout",
      next: 166,
    },
  {
      speaker: "Мишган",
      text: "За ним беги, бля! Я уже лежу, я никуда не денусь!",
      left: "Мишган",
      right: "Охранник",
      leftEmotion: "angry",
      tone: "danger",
      next: 167,
    },
  {
      speaker: "Охранник",
      text: "Молчи!",
      left: "Мишган",
      right: "Охранник",
      rightEmotion: "angry",
      tone: "danger",
      next: 168,
    },
  {
      speaker: "Мишган",
      text: "Уф-уф… Дмит, сука!",
      left: "Мишган",
      right: "Охранник",
      leftEmotion: "sad",
      tone: "danger",
      next: 169,
    },
  {
      speaker: "Рассказчик",
      text: "Дмит вылетает за калитку и бежит до ближайшего двора. Свобода оказывается кислой на вкус: вроде убежал, но в груди что-то неприятно стучит не от бега.",
      left: "Дмит",
      background: "school",
      sound: "dmit-run",
      next: 170,
    },
  {
      speaker: "Дмит",
      text: "Фух… пиздец.",
      left: "Дмит",
      leftEmotion: "sad",
      next: 171,
    },
  {
      speaker: "Рассказчик",
      text: "Он ждёт минуту. Потом ещё одну. Мишган не появляется. Ветер гоняет по асфальту бумажку, похожую на справку о том, что Дмит сегодня поступил как мудак.",
      left: "Дмит",
      leftEmotion: "sad",
      next: 172,
    },
  {
      speaker: "Дмит",
      text: "Сам же сказал валить.",
      left: "Дмит",
      leftEmotion: "thinking",
      next: 173,
    },
  {
      speaker: "Рассказчик",
      text: "Телефон в кармане вибрирует. На экране сообщение от Мишгана.",
      left: "Дмит",
      leftEmotion: "sad",
      sound: "phone-vibrate",
      next: 174,
    },
  {
      speaker: "Мишган",
      text: "Меня к директору ведут.",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "sad",
      phoneMessage: { contact: "Мишган", direction: "incoming" },
      next: 175,
    },
  {
      speaker: "Дмит",
      text: "Бля.",
      left: "Дмит",
      right: "Мишган",
      leftEmotion: "sad",
      phoneMessage: { contact: "Мишган", direction: "outgoing" },
      next: 176,
    },
  {
      speaker: "Мишган",
      text: "Один раунд ты выиграл.",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "sad",
      phoneMessage: { contact: "Мишган", direction: "incoming" },
      next: 177,
    },
  {
      speaker: "Мишган",
      text: "Но своих на ринге не бросают.",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "sad",
      phoneMessage: { contact: "Мишган", direction: "incoming" },
      next: 178,
    },
  {
      speaker: "Дмит",
      text: "Мишган, я бы нас двоих не вытащил.",
      left: "Дмит",
      right: "Мишган",
      leftEmotion: "sad",
      phoneMessage: { contact: "Мишган", direction: "outgoing" },
      next: 179,
    },
  {
      speaker: "Мишган",
      text: "Ага.",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "sad",
      phoneMessage: { contact: "Мишган", direction: "incoming" },
      next: 180,
    },
  {
      speaker: "Дмит",
      text: "Не обижайся.",
      left: "Дмит",
      right: "Мишган",
      leftEmotion: "sad",
      phoneMessage: { contact: "Мишган", direction: "outgoing" },
      next: 181,
    },
  {
      speaker: "Мишган",
      text: "Я не обиделся. Просто в следующий раз спаррингуй сам с собой.",
      left: "Дмит",
      right: "Мишган",
      rightEmotion: "sad",
      phoneMessage: { contact: "Мишган", direction: "incoming" },
      next: 182,
    },
  {
      speaker: "Рассказчик",
      text: "Мишган больше не отвечает. Двор вокруг вроде тот же самый, но Дмит впервые чувствует, что путь к верхушке Арбеково может идти не только вверх.",
      left: "Дмит",
      leftEmotion: "sad",
      background: "school",
      sound: "quest-complete",
      next: 183,
    },
  {
      speaker: "Дмит",
      text: "Вот же бля…",
      left: "Дмит",
      leftEmotion: "sad",
      background: "school",
    }
]
