import type { Scene, StoryChoice } from '../../../../types/story'
import {
  interestingPlaceQuestScenes,
  interestingPlaceQuestStartScene,
} from '../interesting-place/scenes'

export const smallSchoolQuestStartScene =
  interestingPlaceQuestStartScene + interestingPlaceQuestScenes.length

type DraftRoute = { flag: string; next: string }
type DraftChoice = Omit<StoryChoice, 'next' | 'failNext'> & {
  next: string
  failNext?: string
}
type DraftScene = Omit<Scene, 'next' | 'nextByFlag' | 'fallbackNext' | 'choices'> & {
  id?: string
  next?: string
  nextByFlag?: DraftRoute[]
  fallbackNext?: string
  choices?: DraftChoice[]
}

const buildScenes = (startIndex: number, drafts: DraftScene[]): Scene[] => {
  const labels = new Map<string, number>()
  drafts.forEach((draft, index) => {
    if (draft.id) labels.set(draft.id, startIndex + index)
  })

  const resolve = (label?: string) => label === undefined ? undefined : labels.get(label)

  return drafts.map(({ id: _id, next, nextByFlag, fallbackNext, choices, ...scene }) => ({
    ...scene,
    next: resolve(next),
    nextByFlag: nextByFlag?.map((route) => ({ flag: route.flag, next: resolve(route.next) ?? startIndex })),
    fallbackNext: resolve(fallbackNext),
    choices: choices?.map((choice) => ({
      ...choice,
      next: resolve(choice.next) ?? startIndex,
      failNext: resolve(choice.failNext),
    })),
  }))
}

const line = (
  speaker: Scene['speaker'],
  text: string,
  next: string,
  left: Scene['left'] = 'Дмит',
  right?: Scene['right'],
  extra: Partial<DraftScene> = {},
): DraftScene => ({
  speaker,
  text,
  left,
  right,
  background: 'school-dark-vaz',
  next,
  ...extra,
})

export const smallSchoolQuestScenes: Scene[] = buildScenes(smallSchoolQuestStartScene, [
  line('Рассказчик', 'После Миньки компания идёт по вечернему Арбекову. Впереди шагают Кед и Данз, позади хромает Мишган, а Дмит время от времени оглядывается, проверяя, не появились ли снова люди Матвея.', 'start-2', 'Дмит', 'Кед', { id: 'start-1' }),
  line('Данз', 'А куда мы вообще идём?', 'start-3', 'Кед', 'Данз', { id: 'start-2' }),
  line('Кед', 'Ты пять минут назад предложил идти куда глаза смотрят.', 'start-4', 'Кед', 'Данз', { id: 'start-3' }),
  line('Данз', 'Мои глаза уже устали.', 'start-5', 'Кед', 'Данз', { id: 'start-4' }),
  line('Мишган', 'Глаза не устают. Они работают на дистанции.', 'start-6', 'Дмит', 'Мишган', { id: 'start-5' }),
  line('Дмит', 'Мишган, у тебя всё работает на дистанции?', 'start-7', 'Дмит', 'Мишган', { id: 'start-6' }),
  line('Мишган', 'Кроме Данза. Он вообще не работает.', 'start-8', 'Данз', 'Мишган', { id: 'start-7' }),
  line('Данз', 'Я мэр.', 'start-9', 'Кед', 'Данз', { id: 'start-8' }),
  line('Кед', 'Ты безработный мэр.', 'start-10', 'Кед', 'Данз', { id: 'start-9' }),
  line('Данз', 'Зато народный.', 'start-11', 'Кед', 'Данз', { id: 'start-10' }),
  line('Дмит', 'У тебя из народа один админ и какой-то мужик, который притворяется девушкой.', 'start-12', 'Дмит', 'Данз', { id: 'start-11' }),
  line('Данз', 'Не доказано.', 'start-13', 'Дмит', 'Данз', { id: 'start-12' }),
  line('Рассказчик', 'Ребята сворачивают к школе № 76. Днём здесь постоянно орут дети и учителя, но ночью здание выглядит непривычно тихим.', 'school-1', 'Дмит', 'Кед', { id: 'start-13' }),
  line('Кед', 'Чё мы к школе пришли?', 'school-2', 'Дмит', 'Кед', { id: 'school-1' }),
  line('Дмит', 'Короткая дорога.', 'school-3', 'Дмит', 'Кед', { id: 'school-2' }),
  line('Данз', 'Я в школу ночью не пойду. Там географичка живёт.', 'school-4', 'Дмит', 'Данз', { id: 'school-3' }),
  line('Мишган', 'Она ночью висит под потолком.', 'school-5', 'Данз', 'Мишган', { id: 'school-4' }),
  line('Данз', 'Вот именно.', 'school-6', 'Данз', 'Мишган', { id: 'school-5' }),
  line('Кед', 'Вы два дебила.', 'school-7', 'Кед', 'Данз', { id: 'school-6' }),
  line('Дмит', 'Тихо.', 'vadim-1', 'Дмит', 'Кед', { id: 'school-7' }),
  line('Рассказчик', 'Возле школьного забора кто-то сидит на корточках рядом с велосипедом. На земле лежит снятая цепь, а экран телефона освещает знакомое лицо.', 'vadim-2', 'Дмит', undefined, { id: 'vadim-1' }),
  line('Дмит', 'Вадим?', 'vadim-3', 'Дмит', 'Вадим', { id: 'vadim-2' }),
  line('Рассказчик', 'Парень поднимает голову. Это Вадим — ученик из младших классов, которого Дмит несколько раз видел в коридорах школы.', 'vadim-4', 'Дмит', 'Вадим', { id: 'vadim-3' }),
  line('Вадим', 'Здравствуйте.', 'vadim-5', 'Дмит', 'Вадим', { id: 'vadim-4' }),
  line('Дмит', 'Какое ещё «здравствуйте»? Ты чё здесь делаешь?', 'vadim-6', 'Дмит', 'Вадим', { id: 'vadim-5' }),
  line('Вадим', 'В данный момент пытаюсь починить цепь. До этого пытался попасть в школу.', 'vadim-7', 'Дмит', 'Вадим', { id: 'vadim-6' }),
  line('Данз', 'Ночью?', 'vadim-8', 'Данз', 'Вадим', { id: 'vadim-7' }),
  line('Вадим', 'Нет, Данз. Днём. Просто ремонт занял восемь часов.', 'vadim-9', 'Данз', 'Вадим', { id: 'vadim-8' }),
  line('Данз', 'А, понял.', 'vadim-10', 'Кед', 'Данз', { id: 'vadim-9' }),
  line('Кед', 'Он тебя унизил.', 'vadim-11', 'Кед', 'Вадим', { id: 'vadim-10' }),
  line('Вадим', 'Я просто ответил.', 'vadim-12', 'Кед', 'Вадим', { id: 'vadim-11' }),
  line('Мишган', 'Спокойный малый. Уф-уф.', 'vadim-13', 'Мишган', 'Вадим', { id: 'vadim-12' }),
  line('Дмит', 'А ты откуда Данза знаешь?', 'vadim-14', 'Дмит', 'Вадим', { id: 'vadim-13' }),
  line('Вадим', 'Он однажды заходил в кабинет информатики и спрашивал, можно ли установить САМП на учительский компьютер.', 'vadim-15', 'Данз', 'Вадим', { id: 'vadim-14' }),
  line('Данз', 'Я думал, там хороший интернет.', 'vadim-16', 'Данз', 'Вадим', { id: 'vadim-15' }),
  line('Вадим', 'Там Windows 98.', 'vadim-17', 'Данз', 'Вадим', { id: 'vadim-16' }),
  line('Данз', 'Поэтому и не установилось.', 'vadim-18', 'Данз', 'Вадим', { id: 'vadim-17' }),
  line('Кед', 'Конечно. Только поэтому.', 'state-route', 'Кед', 'Данз', {
    id: 'vadim-18',
    nextByFlag: [
      { flag: 'CHAPTER_1_ALCOHOL_SOBER', next: 'sober-1' },
      { flag: 'CHAPTER_1_ALCOHOL_BEER', next: 'beer-1' },
      { flag: 'CHAPTER_1_ALCOHOL_HEAVY', next: 'heavy-1' },
    ],
    fallbackNext: 'sober-1',
  }),

  line('Вадим', 'Вы гуляете?', 'sober-2', 'Дмит', 'Вадим', { id: 'sober-1' }),
  line('Дмит', 'Ага.', 'sober-3', 'Дмит', 'Вадим', { id: 'sober-2' }),
  line('Вадим', 'Ты единственный, от кого не пахнет алкоголем.', 'sober-4', 'Дмит', 'Вадим', { id: 'sober-3' }),
  line('Дмит', 'Потому что я не пил.', 'sober-5', 'Дмит', 'Вадим', { id: 'sober-4' }),
  line('Вадим', 'Разумно.', 'sober-6', 'Дмит', 'Вадим', { id: 'sober-5' }),
  line('Данз', 'Он предал коллектив.', 'sober-7', 'Дмит', 'Данз', { id: 'sober-6' }),
  line('Дмит', 'Зато я дорогу вижу.', 'sober-8', 'Дмит', 'Кед', { id: 'sober-7' }),
  line('Кед', 'Мы тоже видим.', 'sober-9', 'Дмит', 'Кед', { id: 'sober-8' }),
  line('Дмит', 'Ты пять минут назад столб обошёл и извинился перед ним.', 'sober-10', 'Дмит', 'Кед', { id: 'sober-9' }),
  line('Кед', 'Он внезапно появился.', 'sober-11', 'Кед', 'Вадим', { id: 'sober-10' }),
  line('Вадим', 'Хорошо, что ты трезвый.', 'sober-12', 'Дмит', 'Вадим', { id: 'sober-11' }),
  line('Дмит', 'Почему?', 'sober-13', 'Дмит', 'Вадим', { id: 'sober-12' }),
  line('Вадим', 'Потому что мне, кажется, нужна помощь взрослого.', 'sober-14', 'Дмит', 'Вадим', { id: 'sober-13' }),
  line('Дмит', 'Я не взрослый.', 'sober-end', 'Дмит', 'Вадим', { id: 'sober-14' }),
  line('Вадим', 'Ты старше меня.', 'bike-1', 'Дмит', 'Вадим', {
    id: 'sober-end',
    effects: {
      experience: 5,
      flags: ['VADIM_NOTICED_DMIT_SOBER'],
    },
  }),

  line('Вадим', 'Вы пили?', 'beer-2', 'Дмит', 'Вадим', { id: 'beer-1' }),
  line('Дмит', 'Чуть-чуть.', 'beer-3', 'Дмит', 'Вадим', { id: 'beer-2' }),
  line('Вадим', 'От тебя пахнет пивом.', 'beer-4', 'Дмит', 'Вадим', { id: 'beer-3' }),
  line('Дмит', 'Я же говорю — чуть-чуть.', 'beer-5', 'Дмит', 'Вадим', { id: 'beer-4' }),
  line('Данз', 'Это медицинская доза.', 'beer-6', 'Кед', 'Данз', { id: 'beer-5' }),
  line('Кед', 'Не говори слово «медицинская».', 'beer-7', 'Кед', 'Вадим', { id: 'beer-6' }),
  line('Вадим', 'Ты сейчас собираешься помогать мне в таком состоянии?', 'beer-8', 'Дмит', 'Вадим', { id: 'beer-7' }),
  line('Дмит', 'Я ещё не собираюсь.', 'beer-9', 'Дмит', 'Вадим', { id: 'beer-8' }),
  line('Вадим', 'Хорошо.', 'beer-10', 'Дмит', 'Вадим', { id: 'beer-9' }),
  line('Дмит', 'Чё хорошего?', 'beer-11', 'Дмит', 'Вадим', { id: 'beer-10' }),
  line('Вадим', 'Есть время подумать.', 'beer-12', 'Дмит', 'Вадим', { id: 'beer-11' }),
  line('Мишган', 'Он тебя тоже унизил.', 'beer-13', 'Мишган', 'Вадим', { id: 'beer-12' }),
  line('Вадим', 'Я снова просто ответил.', 'bike-1', 'Мишган', 'Вадим', {
    id: 'beer-13',
    effects: {
      experience: 3,
      flags: ['VADIM_SMELLED_ALCOHOL'],
    },
  }),

  line('Вадим', 'Дмит, ты нормально себя чувствуешь?', 'heavy-2', 'Дмит', 'Вадим', { id: 'heavy-1' }),
  line('Дмит', 'А чё со мной?', 'heavy-3', 'Дмит', 'Вадим', { id: 'heavy-2' }),
  line('Вадим', 'Ты стоишь немного боком.', 'heavy-4', 'Дмит', 'Вадим', { id: 'heavy-3' }),
  line('Дмит', 'Я всегда так стою.', 'heavy-5', 'Дмит', 'Вадим', { id: 'heavy-4' }),
  line('Кед', 'Нет.', 'heavy-6', 'Дмит', 'Кед', { id: 'heavy-5' }),
  line('Данз', 'Это боевая стойка алкоголика.', 'heavy-7', 'Кед', 'Данз', { id: 'heavy-6' }),
  line('Мишган', 'Не боевая. Ноги вообще не поставлены.', 'heavy-8', 'Данз', 'Мишган', { id: 'heavy-7' }),
  line('Дмит', 'Да нормально я стою.', 'heavy-9', 'Дмит', 'Вадим', { id: 'heavy-8' }),
  line('Рассказчик', 'Дмит делает шаг к велосипеду и задевает носком лежащую цепь.', 'heavy-10', 'Дмит', 'Вадим', { id: 'heavy-9' }),
  line('Вадим', 'Осторожно.', 'heavy-11', 'Дмит', 'Вадим', { id: 'heavy-10' }),
  line('Дмит', 'Я видел.', 'heavy-12', 'Дмит', 'Вадим', { id: 'heavy-11' }),
  line('Вадим', 'Ты наступил на неё.', 'heavy-13', 'Дмит', 'Вадим', { id: 'heavy-12' }),
  line('Дмит', 'Теперь увидел.', 'heavy-14', 'Дмит', 'Вадим', { id: 'heavy-13' }),
  line('Вадим', 'Мне действительно нужна помощь. Но я пока не уверен, что именно твоя.', 'heavy-15', 'Дмит', 'Вадим', { id: 'heavy-14' }),
  line('Дмит', 'Да не выёбывайся, мелкий.', 'heavy-16', 'Дмит', 'Вадим', { id: 'heavy-15' }),
  line('Вадим', 'Я не выёбываюсь. Я оцениваю риски.', 'heavy-17', 'Дмит', 'Вадим', { id: 'heavy-16' }),
  line('Кед', 'Умный пацан.', 'heavy-18', 'Кед', 'Вадим', { id: 'heavy-17' }),
  line('Данз', 'Я тоже умею оценивать риски.', 'heavy-19', 'Кед', 'Данз', { id: 'heavy-18' }),
  line('Кед', 'Ты сегодня ногой в Мишгана влетел.', 'heavy-20', 'Кед', 'Данз', { id: 'heavy-19' }),
  line('Данз', 'Риск был высокий.', 'bike-1', 'Данз', 'Вадим', {
    id: 'heavy-20',
    effects: {
      experience: 2,
      flags: ['VADIM_SAW_DMIT_DRUNK'],
    },
  }),

  line('Дмит', 'Давно тут сидишь?', 'bike-2', 'Дмит', 'Вадим', { id: 'bike-1' }),
  line('Вадим', 'Тридцать семь минут.', 'bike-3', 'Дмит', 'Вадим', { id: 'bike-2' }),
  line('Данз', 'Ты засекал?', 'bike-4', 'Данз', 'Вадим', { id: 'bike-3' }),
  line('Вадим', 'Да.', 'bike-5', 'Данз', 'Вадим', { id: 'bike-4' }),
  line('Данз', 'Зачем?', 'bike-6', 'Данз', 'Вадим', { id: 'bike-5' }),
  line('Вадим', 'Чтобы знать, давно ли я здесь сижу.', 'bike-7', 'Кед', 'Вадим', { id: 'bike-6' }),
  line('Кед', 'Логично.', 'bike-8', 'Кед', 'Вадим', { id: 'bike-7' }),
  line('Дмит', 'А цепь чё?', 'bike-9', 'Дмит', 'Вадим', { id: 'bike-8' }),
  line('Вадим', 'Соскочила. Потом застряла между звездой и рамой. Я попытался достать её отвёрткой.', 'bike-10', 'Дмит', 'Вадим', { id: 'bike-9' }),
  line('Дмит', 'Получилось?', 'bike-11', 'Дмит', 'Вадим', { id: 'bike-10' }),
  line('Вадим', 'Отвёртка теперь тоже застряла.', 'bike-12', 'Дмит', 'Вадим', { id: 'bike-11' }),
  line('Данз', 'Профессиональный ремонт.', 'bike-13', 'Данз', 'Вадим', { id: 'bike-12' }),
  line('Вадим', 'Ты можешь помочь.', 'bike-14', 'Данз', 'Вадим', { id: 'bike-13' }),
  line('Данз', 'Я в велосипедах не разбираюсь.', 'bike-15', 'Данз', 'Вадим', { id: 'bike-14' }),
  line('Вадим', 'Я имел в виду — можешь не комментировать.', 'bike-16', 'Кед', 'Вадим', { id: 'bike-15' }),
  line('Кед', 'Хороший парень.', 'bike-17', 'Кед', 'Вадим', { id: 'bike-16' }),
  line('Мишган', 'Ударов не наносит, а попадает точно.', 'bike-18', 'Мишган', 'Вадим', { id: 'bike-17' }),
  line('Дмит', 'Родителям звонил?', 'bike-19', 'Дмит', 'Вадим', { id: 'bike-18' }),
  line('Вадим', 'Звонил.', 'bike-20', 'Дмит', 'Вадим', { id: 'bike-19' }),
  line('Дмит', 'И?', 'bike-21', 'Дмит', 'Вадим', { id: 'bike-20' }),
  line('Вадим', 'Не ответили.', 'bike-22', 'Дмит', 'Вадим', { id: 'bike-21' }),
  line('Дмит', 'Ещё позвони.', 'bike-23', 'Дмит', 'Вадим', { id: 'bike-22' }),
  line('Вадим', 'Я звонил четыре раза.', 'bike-24', 'Дмит', 'Вадим', { id: 'bike-23' }),
  line('Данз', 'На пятый открывается секретная концовка.', 'bike-25', 'Данз', 'Вадим', { id: 'bike-24' }),
  line('Вадим', 'На пятый отец поймёт, что я задержался.', 'bike-26', 'Дмит', 'Вадим', { id: 'bike-25' }),
  line('Дмит', 'А он сейчас не поймёт?', 'bike-27', 'Дмит', 'Вадим', { id: 'bike-26' }),
  line('Вадим', 'Сейчас он может думать, что я у одноклассника.', 'bike-28', 'Кед', 'Вадим', { id: 'bike-27' }),
  line('Кед', 'А ты сказал, что будешь у одноклассника?', 'bike-29', 'Кед', 'Вадим', { id: 'bike-28' }),
  line('Вадим', 'Нет.', 'bike-30', 'Кед', 'Вадим', { id: 'bike-29' }),
  line('Кед', 'Тогда с чего он так подумает?', 'bike-31', 'Кед', 'Вадим', { id: 'bike-30' }),
  line('Вадим', 'Я надеюсь, что он выберет самое спокойное объяснение.', 'bike-32', 'Дмит', 'Вадим', { id: 'bike-31' }),
  line('Дмит', 'Взрослые так не умеют.', 'bike-33', 'Дмит', 'Мишган', { id: 'bike-32' }),
  line('Мишган', 'Они сразу представляют похищение, драку и сломанные ноги.', 'bike-34', 'Данз', 'Мишган', { id: 'bike-33' }),
  line('Данз', 'Иногда всё вместе.', 'bike-35', 'Данз', 'Вадим', { id: 'bike-34' }),
  line('Вадим', 'Спасибо. Мне стало спокойнее.', 'bike-choice', 'Дмит', 'Вадим', { id: 'bike-35' }),
  {
    id: 'bike-choice',
    speaker: 'Рассказчик',
    text: 'Дмит смотрит на велосипед, на Вадима и на школьный забор. Можно разобраться внимательнее, а можно сразу спросить главное.',
    left: 'Дмит',
    right: 'Вадим',
    background: 'school-dark-vaz',
    choices: [
      {
        label: '[Внимательность 4] Осмотреть велосипед и вещи Вадима.',
        shortLabel: 'Осмотреть велосипед и вещи Вадима.',
        narration: 'Дмит присаживается возле велосипеда и внимательно осматривает цепь, раму и всё, что валяется рядом.',
        requires: { perception: 4 },
        next: 'inspect-success-1',
        failNext: 'inspect-skip-1',
        failureText: 'Дмит присаживается возле велосипеда, но в темноте видит только цепь, отвёртку и собственное желание поскорее перейти к сути.',
      },
      {
        label: 'Да хуй с велосипедом. Объясняй, зачем тебе в школу.',
        shortLabel: 'Спросить про школу.',
        next: 'inspect-skip-1',
      },
    ],
  },

  line('Рассказчик', 'Дмит присаживается возле велосипеда и внимательно смотрит на цепь.', 'inspect-success-2', 'Дмит', 'Вадим', { id: 'inspect-success-1' }),
  line('Дмит', 'Она не порвалась.', 'inspect-success-3', 'Дмит', 'Вадим', { id: 'inspect-success-2' }),
  line('Вадим', 'Нет. Просто сильно застряла.', 'inspect-success-4', 'Дмит', 'Вадим', { id: 'inspect-success-3' }),
  line('Дмит', 'А это чё?', 'inspect-success-5', 'Дмит', 'Вадим', { id: 'inspect-success-4' }),
  line('Рассказчик', 'На раме возле заднего колеса видна свежая царапина. Рядом в траве лежит смятый чёрный пластиковый хомут.', 'inspect-success-6', 'Дмит', 'Вадим', { id: 'inspect-success-5' }),
  line('Вадим', 'Не знаю.', 'inspect-success-7', 'Кед', 'Вадим', { id: 'inspect-success-6' }),
  line('Кед', 'Может, цепь хомутом держалась?', 'inspect-success-8', 'Кед', 'Вадим', { id: 'inspect-success-7' }),
  line('Вадим', 'Нет. Я слежу за велосипедом.', 'inspect-success-9', 'Данз', 'Вадим', { id: 'inspect-success-8' }),
  line('Данз', 'Кто-то пытался его связать.', 'inspect-success-10', 'Дмит', 'Данз', { id: 'inspect-success-9' }),
  line('Дмит', 'Кто-то мог дёрнуть цепь или колесо.', 'inspect-success-11', 'Дмит', 'Вадим', { id: 'inspect-success-10' }),
  line('Вадим', 'Когда я оставил велосипед, он был исправен.', 'inspect-success-12', 'Мишган', 'Вадим', { id: 'inspect-success-11' }),
  line('Мишган', 'Значит, был удар.', 'inspect-success-13', 'Дмит', 'Мишган', { id: 'inspect-success-12' }),
  line('Дмит', 'Не всё в мире удар.', 'inspect-success-14', 'Дмит', 'Мишган', { id: 'inspect-success-13' }),
  line('Мишган', 'Но здесь след есть.', 'inspect-success-15', 'Дмит', 'Мишган', { id: 'inspect-success-14' }),
  line('Рассказчик', 'Дмит замечает на руле велосипеда тонкую белую пыль.', 'inspect-success-16', 'Дмит', 'Вадим', { id: 'inspect-success-15' }),
  line('Дмит', 'Это мел?', 'inspect-success-17', 'Дмит', 'Вадим', { id: 'inspect-success-16' }),
  line('Вадим', 'Возможно. Я ставил велосипед у стены возле спортивного входа.', 'inspect-success-18', 'Кед', 'Вадим', { id: 'inspect-success-17' }),
  line('Кед', 'Там вечером старшие курят.', 'inspect-success-19', 'Кед', 'Вадим', { id: 'inspect-success-18' }),
  line('Вадим', 'Я никого не видел.', 'inspect-success-20', 'Дмит', 'Вадим', { id: 'inspect-success-19' }),
  line('Дмит', 'Может, увидишь потом.', 'inspect-success-21', 'Дмит', 'Вадим', {
    id: 'inspect-success-20',
    effects: { experience: 5, flags: ['VADIM_BIKE_SABOTAGE_NOTICED'] },
  }),
  line('Вадим', 'Ты быстро заметил.', 'inspect-success-22', 'Дмит', 'Вадим', { id: 'inspect-success-21' }),
  line('Дмит', 'Я просто смотрю.', 'inspect-success-23', 'Дмит', 'Вадим', { id: 'inspect-success-22' }),
  line('Вадим', 'В школе это не очень заметно.', 'inspect-success-24', 'Дмит', 'Вадим', { id: 'inspect-success-23' }),
  line('Дмит', 'Не начинай.', 'inspect-success-25', 'Дмит', 'Вадим', { id: 'inspect-success-24' }),
  line('Вадим', 'Хорошо.', 'backpack-1', 'Дмит', 'Вадим', { id: 'inspect-success-25' }),

  line('Дмит', 'Да хуй с велосипедом. Объясняй, зачем тебе в школу.', 'inspect-skip-2', 'Дмит', 'Вадим', { id: 'inspect-skip-1' }),
  line('Вадим', 'Я как раз пытался.', 'inspect-skip-3', 'Дмит', 'Вадим', { id: 'inspect-skip-2' }),
  line('Дмит', 'Так пытайся быстрее.', 'inspect-skip-4', 'Дмит', 'Вадим', { id: 'inspect-skip-3' }),
  line('Вадим', 'Хорошо.', 'backpack-1', 'Дмит', 'Вадим', { id: 'inspect-skip-4' }),

  line('Вадим', 'Я готовился к городской олимпиаде по информатике.', 'backpack-2', 'Данз', 'Вадим', { id: 'backpack-1' }),
  line('Данз', 'По САМПу?', 'backpack-3', 'Данз', 'Вадим', { id: 'backpack-2' }),
  line('Вадим', 'Нет.', 'backpack-4', 'Данз', 'Вадим', { id: 'backpack-3' }),
  line('Данз', 'Жаль. Я бы выиграл.', 'backpack-5', 'Данз', 'Вадим', { id: 'backpack-4' }),
  line('Вадим', 'Ты не смог установить игру на Windows 98.', 'backpack-6', 'Данз', 'Вадим', { id: 'backpack-5' }),
  line('Данз', 'Это была несовместимость систем.', 'backpack-7', 'Кед', 'Данз', { id: 'backpack-6' }),
  line('Кед', 'Дай ему договорить.', 'backpack-8', 'Кед', 'Вадим', { id: 'backpack-7' }),
  line('Вадим', 'После занятий я остался в кабинете информатики. Мы с учителем проверяли проект.', 'backpack-9', 'Дмит', 'Вадим', { id: 'backpack-8' }),
  line('Дмит', 'Какой проект?', 'backpack-10', 'Дмит', 'Вадим', { id: 'backpack-9' }),
  line('Вадим', 'Программа, которая строит оптимальный маршрут по городу.', 'backpack-11', 'Данз', 'Вадим', { id: 'backpack-10' }),
  line('Данз', 'Такси?', 'backpack-12', 'Данз', 'Вадим', { id: 'backpack-11' }),
  line('Вадим', 'Приблизительно.', 'backpack-13', 'Данз', 'Вадим', { id: 'backpack-12' }),
  line('Данз', 'Я же говорил, что мэром стал не просто так.', 'backpack-14', 'Данз', 'Вадим', { id: 'backpack-13' }),
  line('Вадим', 'Ты не имеешь к проекту никакого отношения.', 'backpack-15', 'Дмит', 'Вадим', { id: 'backpack-14' }),
  line('Дмит', 'Дальше чё?', 'backpack-16', 'Дмит', 'Вадим', { id: 'backpack-15' }),
  line('Вадим', 'Я ушёл через спортивный вход. Только возле дома понял, что оставил рюкзак в кабинете.', 'backpack-17', 'Кед', 'Вадим', { id: 'backpack-16' }),
  line('Кед', 'Вернулся?', 'backpack-18', 'Кед', 'Вадим', { id: 'backpack-17' }),
  line('Вадим', 'Да. Но школа уже была закрыта.', 'backpack-19', 'Дмит', 'Вадим', { id: 'backpack-18' }),
  line('Дмит', 'Чё там такого важного?', 'backpack-20', 'Дмит', 'Вадим', { id: 'backpack-19' }),
  line('Вадим', 'Документы на олимпиаду, распечатанный проект и флешка.', 'backpack-21', 'Данз', 'Вадим', { id: 'backpack-20' }),
  line('Данз', 'На флешке есть игры?', 'backpack-22', 'Данз', 'Вадим', { id: 'backpack-21' }),
  line('Вадим', 'На ней три месяца моей работы.', 'backpack-23', 'Данз', 'Вадим', { id: 'backpack-22' }),
  line('Данз', 'То есть нет.', 'backpack-24', 'Данз', 'Вадим', { id: 'backpack-23' }),
  line('Вадим', 'Нет.', 'backpack-25', 'Дмит', 'Вадим', { id: 'backpack-24' }),
  line('Дмит', 'А завтра забрать нельзя?', 'backpack-26', 'Дмит', 'Вадим', { id: 'backpack-25' }),
  line('Вадим', 'В семь утра учитель уезжает с командой. Если я не передам ему документы, меня не зарегистрируют.', 'backpack-27', 'Кед', 'Вадим', { id: 'backpack-26' }),
  line('Кед', 'Хуёво.', 'backpack-28', 'Кед', 'Вадим', { id: 'backpack-27' }),
  line('Вадим', 'Да.', 'backpack-29', 'Мишган', 'Вадим', { id: 'backpack-28' }),
  line('Мишган', 'Первый раз слышу, как он согласился с матом.', 'backpack-30', 'Мишган', 'Вадим', { id: 'backpack-29' }),
  line('Вадим', 'Ситуация соответствует.', 'post-backpack-route', 'Дмит', 'Вадим', {
    id: 'backpack-30',
    nextByFlag: [
      { flag: 'DMIT_DAMAGED', next: 'injury-1' },
      { flag: 'MATVEY_DEFEATED', next: 'matvey-win-1' },
      { flag: 'MATVEY_HUMILIATED_DMIT', next: 'matvey-humiliation-1' },
    ],
    fallbackNext: 'quest-pause',
  }),

  line('Вадим', 'У тебя кровь на губе.', 'injury-2', 'Дмит', 'Вадим', { id: 'injury-1' }),
  line('Дмит', 'Уже нет.', 'injury-3', 'Дмит', 'Вадим', { id: 'injury-2' }),
  line('Вадим', 'Есть.', 'injury-4', 'Дмит', 'Вадим', { id: 'injury-3' }),
  line('Дмит', 'Это старая.', 'injury-5', 'Дмит', 'Вадим', { id: 'injury-4' }),
  line('Вадим', 'Кровь не становится новой или старой за двадцать минут.', 'injury-6', 'Данз', 'Вадим', { id: 'injury-5' }),
  line('Данз', 'Смотря где хранить.', 'injury-7', 'Кед', 'Данз', { id: 'injury-6' }),
  line('Кед', 'Данз.', 'injury-8', 'Кед', 'Данз', { id: 'injury-7' }),
  line('Данз', 'Молчу.', 'injury-9', 'Данз', 'Вадим', { id: 'injury-8' }),
  line('Вадим', 'Вы дрались?', 'injury-10', 'Мишган', 'Вадим', { id: 'injury-9' }),
  line('Мишган', 'Был конфликт за территорию.', 'injury-11', 'Дмит', 'Мишган', { id: 'injury-10' }),
  line('Дмит', 'Да просто один долбоёб полез.', 'injury-12', 'Дмит', 'Вадим', { id: 'injury-11' }),
  line('Вадим', 'И теперь ты собираешься лезть через школьный забор с травмой головы?', 'injury-13', 'Дмит', 'Вадим', { id: 'injury-12' }),
  line('Дмит', 'Я ещё никуда не собираюсь.', 'injury-14', 'Дмит', 'Вадим', { id: 'injury-13' }),
  line('Вадим', 'Хорошо. Потому что это звучит ещё хуже, чем алкоголь.', 'post-injury-route', 'Дмит', 'Вадим', {
    id: 'injury-14',
    effects: { flags: ['VADIM_NOTICED_DMIT_INJURY'] },
    nextByFlag: [
      { flag: 'MATVEY_DEFEATED', next: 'matvey-win-1' },
      { flag: 'MATVEY_HUMILIATED_DMIT', next: 'matvey-humiliation-1' },
    ],
    fallbackNext: 'quest-pause',
  }),

  line('Вадим', 'Кстати, о драке.', 'matvey-win-2', 'Дмит', 'Вадим', { id: 'matvey-win-1' }),
  line('Дмит', 'Чё?', 'matvey-win-3', 'Дмит', 'Вадим', { id: 'matvey-win-2' }),
  line('Вадим', 'В школьной беседе пишут, что вы победили Матвея.', 'matvey-win-4', 'Дмит', 'Вадим', { id: 'matvey-win-3' }),
  line('Дмит', 'Уже?', 'matvey-win-5', 'Дмит', 'Вадим', { id: 'matvey-win-4' }),
  line('Вадим', 'Первое сообщение появилось одиннадцать минут назад.', 'matvey-win-6', 'Кед', 'Вадим', { id: 'matvey-win-5' }),
  line('Кед', 'Кто написал?', 'matvey-win-7', 'Кед', 'Вадим', { id: 'matvey-win-6' }),
  line('Вадим', 'Пользователь с именем «Король_Арбеково_2007».', 'matvey-win-8', 'Данз', 'Вадим', { id: 'matvey-win-7' }),
  line('Данз', 'Уважаемый человек.', 'matvey-win-9', 'Мишган', 'Вадим', { id: 'matvey-win-8' }),
  line('Мишган', 'Написали, как я одного вырубил?', 'matvey-win-10', 'Мишган', 'Вадим', { id: 'matvey-win-9' }),
  line('Вадим', 'Написали, что ты упал после удара Данза.', 'matvey-win-11', 'Мишган', 'Вадим', { id: 'matvey-win-10' }),
  line('Мишган', 'А до этого?', 'matvey-win-12', 'Мишган', 'Вадим', { id: 'matvey-win-11' }),
  line('Вадим', 'Про это не написали.', 'matvey-win-13', 'Мишган', 'Вадим', { id: 'matvey-win-12' }),
  line('Мишган', 'Нечестные СМИ, бля.', 'matvey-win-14', 'Дмит', 'Вадим', { id: 'matvey-win-13' }),
  line('Дмит', 'Матвей чё пишет?', 'matvey-win-15', 'Дмит', 'Вадим', { id: 'matvey-win-14' }),
  line('Вадим', 'Он ничего не пишет. Но его друзья спрашивали, куда вы пошли.', 'matvey-win-16', 'Кед', 'Вадим', { id: 'matvey-win-15' }),
  line('Кед', 'Зачем?', 'matvey-win-17', 'Кед', 'Вадим', { id: 'matvey-win-16' }),
  line('Вадим', 'Предполагаю, что не для извинений.', 'matvey-win-18', 'Дмит', 'Вадим', { id: 'matvey-win-17' }),
  line('Дмит', 'Пусть ищут.', 'matvey-win-19', 'Дмит', 'Вадим', { id: 'matvey-win-18' }),
  line('Вадим', 'Они могут знать, что мы возле школы.', 'matvey-win-20', 'Дмит', 'Вадим', { id: 'matvey-win-19' }),
  line('Дмит', 'С чего?', 'matvey-win-21', 'Дмит', 'Вадим', { id: 'matvey-win-20' }),
  line('Вадим', 'Я написал однокласснику, что нахожусь здесь.', 'matvey-win-22', 'Дмит', 'Вадим', { id: 'matvey-win-21' }),
  line('Дмит', 'Нахуя?', 'matvey-win-23', 'Данз', 'Вадим', { id: 'matvey-win-22' }),
  line('Вадим', 'Я просил принести инструмент.', 'matvey-win-24', 'Данз', 'Вадим', { id: 'matvey-win-23' }),
  line('Данз', 'Шпионская сеть раскрыта.', 'quest-pause', 'Данз', 'Вадим', {
    id: 'matvey-win-24',
    effects: { flags: ['MATVEY_CREW_MAY_FIND_SCHOOL'] },
  }),

  line('Вадим', 'Ещё я хотел спросить.', 'matvey-humiliation-2', 'Дмит', 'Вадим', { id: 'matvey-humiliation-1' }),
  line('Дмит', 'Чё?', 'matvey-humiliation-3', 'Дмит', 'Вадим', { id: 'matvey-humiliation-2' }),
  line('Вадим', 'Правда, что Матвей заставил тебя отдать ему пиво?', 'matvey-humiliation-4', 'Дмит', 'Вадим', { id: 'matvey-humiliation-3' }),
  line('Рассказчик', 'Кед смотрит в сторону. Мишган перестаёт улыбаться.', 'matvey-humiliation-5', 'Кед', 'Мишган', { id: 'matvey-humiliation-4' }),
  line('Дмит', 'Кто говорит?', 'matvey-humiliation-6', 'Дмит', 'Вадим', { id: 'matvey-humiliation-5' }),
  line('Вадим', 'Почти вся школа.', 'matvey-humiliation-7', 'Дмит', 'Вадим', { id: 'matvey-humiliation-6' }),
  line('Дмит', 'Когда они успели?', 'matvey-humiliation-8', 'Дмит', 'Вадим', { id: 'matvey-humiliation-7' }),
  line('Вадим', 'У нас есть общая беседа.', 'matvey-humiliation-9', 'Дмит', 'Вадим', { id: 'matvey-humiliation-8' }),
  line('Дмит', 'И чё там написано?', 'matvey-humiliation-10', 'Дмит', 'Вадим', { id: 'matvey-humiliation-9' }),
  line('Вадим', 'Что ты сказал: «Минька Матвея».', 'matvey-humiliation-11', 'Дмит', 'Вадим', { id: 'matvey-humiliation-10' }),
  line('Дмит', 'Пиздят.', 'matvey-humiliation-12', 'Дмит', 'Мишган', { id: 'matvey-humiliation-11' }),
  line('Мишган', 'Не совсем.', 'matvey-humiliation-13', 'Дмит', 'Мишган', { id: 'matvey-humiliation-12' }),
  line('Дмит', 'Мишган.', 'matvey-humiliation-14', 'Дмит', 'Мишган', { id: 'matvey-humiliation-13' }),
  line('Мишган', 'Я молчу.', 'matvey-humiliation-15', 'Дмит', 'Вадим', { id: 'matvey-humiliation-14' }),
  line('Вадим', 'Я не хотел тебя обидеть.', 'matvey-humiliation-16', 'Дмит', 'Вадим', { id: 'matvey-humiliation-15' }),
  line('Дмит', 'Тогда нахуя спросил?', 'matvey-humiliation-17', 'Дмит', 'Вадим', { id: 'matvey-humiliation-16' }),
  line('Вадим', 'Хотел понять, можно ли на тебя рассчитывать.', 'matvey-humiliation-18', 'Дмит', 'Вадим', { id: 'matvey-humiliation-17' }),
  line('Дмит', 'И чё понял?', 'matvey-humiliation-19', 'Дмит', 'Вадим', { id: 'matvey-humiliation-18' }),
  line('Вадим', 'Пока не понял.', 'matvey-humiliation-20', 'Дмит', 'Вадим', { id: 'matvey-humiliation-19' }),
  line('Рассказчик', 'Дмит замечает, что Кед и Мишган ждут его ответа.', 'quest-pause', 'Дмит', 'Вадим', {
    id: 'matvey-humiliation-20',
    effects: { flags: ['VADIM_HEARD_ABOUT_HUMILIATION'] },
  }),

  line('Дмит', 'Ладно. Ты чё сам собирался делать?', 'plan-2', 'Дмит', 'Вадим', { id: 'quest-pause' }),
  line('Вадим', 'Перелезть через забор.', 'plan-3', 'Дмит', 'Вадим', { id: 'plan-2' }),
  line('Дмит', 'Ты?', 'plan-4', 'Дмит', 'Вадим', { id: 'plan-3' }),
  line('Вадим', 'Да.', 'plan-5', 'Кед', 'Вадим', { id: 'plan-4' }),
  line('Кед', 'А дальше?', 'plan-6', 'Кед', 'Вадим', { id: 'plan-5' }),
  line('Вадим', 'В раздевалке на первом этаже плохо закрывается окно.', 'plan-7', 'Данз', 'Вадим', { id: 'plan-6' }),
  line('Данз', 'Откуда знаешь?', 'plan-8', 'Данз', 'Вадим', { id: 'plan-7' }),
  line('Вадим', 'Дежурил там на прошлой неделе.', 'plan-9', 'Мишган', 'Вадим', { id: 'plan-8' }),
  line('Мишган', 'Разведка проведена.', 'plan-10', 'Мишган', 'Вадим', { id: 'plan-9' }),
  line('Вадим', 'Я бы открыл окно, прошёл в кабинет информатики, забрал рюкзак и вышел.', 'plan-11', 'Дмит', 'Вадим', { id: 'plan-10' }),
  line('Дмит', 'А охранник?', 'plan-12', 'Дмит', 'Вадим', { id: 'plan-11' }),
  line('Вадим', 'Он обычно смотрит телевизор возле главного входа.', 'plan-13', 'Кед', 'Вадим', { id: 'plan-12' }),
  line('Кед', 'Обычно?', 'plan-14', 'Кед', 'Вадим', { id: 'plan-13' }),
  line('Вадим', 'Я видел его три раза.', 'plan-15', 'Дмит', 'Вадим', { id: 'plan-14' }),
  line('Дмит', 'Три раза ночью?', 'plan-16', 'Дмит', 'Вадим', { id: 'plan-15' }),
  line('Вадим', 'Нет. После дополнительных занятий.', 'plan-17', 'Данз', 'Вадим', { id: 'plan-16' }),
  line('Данз', 'То есть твой план основан на дневном охраннике.', 'plan-18', 'Данз', 'Вадим', { id: 'plan-17' }),
  line('Вадим', 'Это тот же человек.', 'plan-19', 'Данз', 'Вадим', { id: 'plan-18' }),
  line('Данз', 'Но ночью он сильнее.', 'plan-20', 'Данз', 'Вадим', { id: 'plan-19' }),
  line('Вадим', 'Почему?', 'plan-21', 'Данз', 'Вадим', { id: 'plan-20' }),
  line('Данз', 'Ночной бонус.', 'plan-22', 'Кед', 'Данз', { id: 'plan-21' }),
  line('Кед', 'Не слушай его.', 'plan-23', 'Дмит', 'Вадим', { id: 'plan-22' }),
  line('Дмит', 'А если окно закрыто?', 'plan-24', 'Дмит', 'Вадим', { id: 'plan-23' }),
  line('Вадим', 'Тогда придётся придумать другой вариант.', 'plan-25', 'Дмит', 'Вадим', { id: 'plan-24' }),
  line('Дмит', 'А если тебя поймают?', 'plan-26', 'Дмит', 'Вадим', { id: 'plan-25' }),
  line('Вадим', 'Скажу правду.', 'plan-27', 'Дмит', 'Вадим', { id: 'plan-26' }),
  line('Дмит', 'Тогда нахуя лезть тайком?', 'plan-28', 'Дмит', 'Вадим', { id: 'plan-27' }),
  line('Вадим', 'Потому что правду лучше говорить после того, как забрал рюкзак.', 'plan-29', 'Кед', 'Вадим', { id: 'plan-28' }),
  line('Кед', 'Не такой он и правильный.', 'plan-30', 'Кед', 'Вадим', { id: 'plan-29' }),
  line('Вадим', 'Я стараюсь быть практичным.', 'key-plan-1', 'Дмит', 'Вадим', { id: 'plan-30' }),

  line('Вадим', 'Дмит, ты ведь знаешь, что делать?', 'key-plan-2', 'Дмит', 'Вадим', { id: 'key-plan-1' }),
  line('Дмит', 'С хуя ли?', 'key-plan-3', 'Дмит', 'Вадим', { id: 'key-plan-2' }),
  line('Вадим', 'Ты старше.', 'key-plan-4', 'Дмит', 'Вадим', { id: 'key-plan-3' }),
  line('Дмит', 'Это вообще ничего не значит.', 'key-plan-5', 'Дмит', 'Вадим', { id: 'key-plan-4' }),
  line('Вадим', 'Для меня значит.', 'key-plan-route', 'Дмит', 'Вадим', { id: 'key-plan-5' }),
  line('Рассказчик', 'Вадим говорит спокойно, но продолжает смотреть именно на Дмита. Остальные тоже ждут его решения.', 'main-choice', 'Дмит', 'Вадим', {
    id: 'key-plan-route',
    nextByFlag: [
      { flag: 'CHAPTER_1_DID_NOT_APOLOGIZE_TO_MISHGAN', next: 'mishgan-bad-1' },
      { flag: 'CHAPTER_1_APOLOGIZED_TO_MISHGAN', next: 'mishgan-apology-1' },
      { flag: 'CHAPTER_1_HELPED_MISHGAN', next: 'mishgan-helped-1' },
    ],
    fallbackNext: 'main-choice',
  }),

  line('Мишган', 'Только ты это… если начнётся погоня, сразу скажи Вадиму, что каждый сам за себя.', 'mishgan-bad-2', 'Дмит', 'Мишган', { id: 'mishgan-bad-1' }),
  line('Дмит', 'Да заебал.', 'mishgan-bad-3', 'Дмит', 'Мишган', { id: 'mishgan-bad-2' }),
  line('Мишган', 'Я просто правила команды уточняю.', 'mishgan-bad-4', 'Дмит', 'Мишган', { id: 'mishgan-bad-3' }),
  line('Вадим', 'Какая погоня?', 'mishgan-bad-5', 'Данз', 'Вадим', { id: 'mishgan-bad-4' }),
  line('Данз', 'Долгая история.', 'mishgan-bad-6', 'Кед', 'Данз', { id: 'mishgan-bad-5' }),
  line('Кед', 'Не сейчас.', 'mishgan-bad-7', 'Кед', 'Вадим', { id: 'mishgan-bad-6' }),
  line('Вадим', 'Дмит кого-то бросил?', 'mishgan-bad-8', 'Дмит', 'Вадим', { id: 'mishgan-bad-7' }),
  line('Дмит', 'Никого я не бросил.', 'mishgan-bad-9', 'Дмит', 'Мишган', { id: 'mishgan-bad-8' }),
  line('Мишган', 'Уф-уф. Значит, я сам лежал, а ты случайно убегал.', 'mishgan-bad-10', 'Дмит', 'Мишган', { id: 'mishgan-bad-9' }),
  line('Дмит', 'Мишган, хорош.', 'mishgan-bad-11', 'Дмит', 'Мишган', { id: 'mishgan-bad-10' }),
  line('Мишган', 'Решай уже.', 'main-choice', 'Дмит', 'Вадим', {
    id: 'mishgan-bad-11',
    effects: { flags: ['VADIM_LEARNED_DMIT_ABANDONED_MISHGAN'] },
  }),

  line('Мишган', 'Вадим, не ссы. Теперь он своих не бросает.', 'mishgan-apology-2', 'Дмит', 'Мишган', { id: 'mishgan-apology-1' }),
  line('Дмит', 'Теперь?', 'mishgan-apology-3', 'Дмит', 'Мишган', { id: 'mishgan-apology-2' }),
  line('Мишган', 'После обновления.', 'mishgan-apology-4', 'Мишган', 'Вадим', { id: 'mishgan-apology-3' }),
  line('Вадим', 'Что было в предыдущей версии?', 'mishgan-apology-5', 'Кед', 'Вадим', { id: 'mishgan-apology-4' }),
  line('Кед', 'Ошибка.', 'mishgan-apology-6', 'Кед', 'Данз', { id: 'mishgan-apology-5' }),
  line('Данз', 'Критическая.', 'mishgan-apology-7', 'Дмит', 'Данз', { id: 'mishgan-apology-6' }),
  line('Дмит', 'Да завалите.', 'mishgan-apology-8', 'Дмит', 'Мишган', { id: 'mishgan-apology-7' }),
  line('Мишган', 'Но исправил же.', 'mishgan-apology-9', 'Дмит', 'Вадим', { id: 'mishgan-apology-8' }),
  line('Вадим', 'Хорошо.', 'mishgan-apology-10', 'Дмит', 'Вадим', { id: 'mishgan-apology-9' }),
  line('Дмит', 'Чё хорошего?', 'mishgan-apology-11', 'Дмит', 'Вадим', { id: 'mishgan-apology-10' }),
  line('Вадим', 'Люди, которые исправляют ошибки, надёжнее людей, которые считают, что никогда не ошибаются.', 'mishgan-apology-12', 'Мишган', 'Вадим', { id: 'mishgan-apology-11' }),
  line('Мишган', 'Умный малый. Я говорил.', 'main-choice', 'Дмит', 'Вадим', {
    id: 'mishgan-apology-12',
    effects: { flags: ['VADIM_KNOWS_DMIT_APOLOGIZED'] },
  }),

  line('Мишган', 'Он поможет.', 'mishgan-helped-2', 'Дмит', 'Мишган', { id: 'mishgan-helped-1' }),
  line('Дмит', 'Я ещё не сказал.', 'mishgan-helped-3', 'Дмит', 'Мишган', { id: 'mishgan-helped-2' }),
  line('Мишган', 'Скажешь.', 'mishgan-helped-4', 'Дмит', 'Мишган', { id: 'mishgan-helped-3' }),
  line('Дмит', 'С чего ты решил?', 'mishgan-helped-5', 'Дмит', 'Мишган', { id: 'mishgan-helped-4' }),
  line('Мишган', 'Ты тогда за мной вернулся.', 'mishgan-helped-6', 'Дмит', 'Мишган', { id: 'mishgan-helped-5' }),
  line('Дмит', 'Мы из-за этого к директору попали.', 'mishgan-helped-7', 'Дмит', 'Мишган', { id: 'mishgan-helped-6' }),
  line('Мишган', 'Зато вместе.', 'mishgan-helped-8', 'Мишган', 'Вадим', { id: 'mishgan-helped-7' }),
  line('Вадим', 'Это положительная рекомендация?', 'mishgan-helped-9', 'Кед', 'Вадим', { id: 'mishgan-helped-8' }),
  line('Кед', 'От Мишгана — да.', 'mishgan-helped-10', 'Кед', 'Мишган', { id: 'mishgan-helped-9' }),
  line('Мишган', 'Уф-уф. Гарантия качества.', 'main-choice', 'Дмит', 'Вадим', { id: 'mishgan-helped-10' }),

  {
    id: 'main-choice',
    speaker: 'Рассказчик',
    text: 'План Вадима звучит одновременно безумно и слишком продуманно для человека, который сидит у забора с застрявшей отвёрткой. Дмит должен решить, что делать дальше.',
    left: 'Дмит',
    right: 'Вадим',
    background: 'school-dark-vaz',
    choices: [
      {
        label: 'Ладно. Полезем в школу и заберём твой рюкзак.',
        shortLabel: 'Помочь Вадиму.',
        next: 'accept-help-1',
        effects: { experience: 8, flags: ['VADIM_HELP_ACCEPTED'] },
      },
      {
        label: 'Пошли домой. Утром вернёшься и спокойно заберёшь.',
        shortLabel: 'Отложить до утра.',
        next: 'send-home-1',
        effects: { experience: 6, flags: ['VADIM_SENT_HOME'] },
      },
      {
        label: 'Это не моя проблема. Сам рюкзак забыл — сам и разбирайся.',
        shortLabel: 'Отказать Вадиму.',
        next: 'refuse-1',
        effects: {
          reputation: -4,
          relations: { Кед: -1, Мишган: -1 },
          flags: ['DMIT_REFUSED_VADIM'],
        },
      },
      {
        label: 'Забей на рюкзак. Пошли с нами гулять.',
        shortLabel: 'Забрать гулять.',
        next: 'night-walk-1',
        effects: { experience: 4, flags: ['VADIM_JOINED_NIGHT_WALK'] },
      },
      {
        label: '[Интеллект 5] Сначала позвоним учителю. Может, он ещё не уехал и откроет школу.',
        shortLabel: 'Позвонить учителю.',
        requires: { intelligence: 5 },
        next: 'teacher-call-success-1',
        failNext: 'teacher-call-fail-1',
        failureText: 'Дмит пытается составить нормальный план звонка учителю, но слова расползаются: получается что-то между официальной просьбой и угрозой районного масштаба.',
        effects: { experience: 10, flags: ['VADIM_TEACHER_CALLED_SUCCESS'] },
        failureEffects: { experience: 3, flags: ['VADIM_TEACHER_CALL_FAILED'] },
      },
      {
        label: '[Внимательность 4] Сначала разберёмся, кто трогал твой велосипед.',
        shortLabel: 'Проверить саботаж велосипеда.',
        requires: { perception: 4 },
        requiresFlags: ['VADIM_BIKE_SABOTAGE_NOTICED'],
        next: 'bike-sabotage-sidequest-1',
        effects: { experience: 6, flags: ['VADIM_CHAIN_SIDEQUEST_STARTED'] },
      },
    ],
  },

  line('Дмит', 'Ладно. Полезем в школу и заберём твой рюкзак.', 'accept-help-2', 'Дмит', 'Вадим', { id: 'accept-help-1' }),
  line('Вадим', 'Ты уверен?', 'accept-help-3', 'Дмит', 'Вадим', { id: 'accept-help-2' }),
  line('Дмит', 'Нет.', 'accept-help-4', 'Дмит', 'Вадим', { id: 'accept-help-3' }),
  line('Вадим', 'Тогда почему согласился?', 'accept-help-5', 'Дмит', 'Вадим', { id: 'accept-help-4' }),
  line('Дмит', 'Потому что если ты полезешь один, тебя поймают через две минуты.', 'accept-help-6', 'Дмит', 'Вадим', { id: 'accept-help-5' }),
  line('Вадим', 'Почему через две?', 'accept-help-7', 'Дмит', 'Вадим', { id: 'accept-help-6' }),
  line('Дмит', 'Через одну тебе будет обидно.', 'accept-help-8', 'Дмит', 'Кед', { id: 'accept-help-7' }),
  line('Кед', 'Я с вами.', 'accept-help-9', 'Кед', 'Данз', { id: 'accept-help-8' }),
  line('Данз', 'Я тоже.', 'accept-help-10', 'Дмит', 'Данз', { id: 'accept-help-9' }),
  line('Дмит', 'Ты останешься снаружи.', 'accept-help-11', 'Дмит', 'Данз', { id: 'accept-help-10' }),
  line('Данз', 'Почему?', 'accept-help-12', 'Кед', 'Данз', { id: 'accept-help-11' }),
  line('Кед', 'Потому что ты при обычном входе в школу умудряешься что-нибудь сломать.', 'accept-help-13', 'Кед', 'Мишган', { id: 'accept-help-12' }),
  line('Мишган', 'Я прикрою отход. Уф-уф, бля.', 'accept-help-14', 'Мишган', 'Вадим', { id: 'accept-help-13' }),
  line('Вадим', 'Только без ударов по охраннику.', 'accept-help-15', 'Мишган', 'Вадим', { id: 'accept-help-14' }),
  line('Мишган', 'Посмотрим на его поведение.', 'accept-help-16', 'Мишган', 'Вадим', { id: 'accept-help-15' }),
  line('Вадим', 'Нет. Не посмотрим.', 'accept-help-17', 'Дмит', 'Вадим', { id: 'accept-help-16' }),
  line('Дмит', 'Так. Сначала решаем, как входим.', 'stage-end-infiltration', 'Дмит', 'Вадим', { id: 'accept-help-17' }),

  line('Дмит', 'Пошли домой. Родителям всё расскажешь, утром будете решать.', 'send-home-2', 'Дмит', 'Вадим', { id: 'send-home-1' }),
  line('Вадим', 'Но олимпиада.', 'send-home-3', 'Дмит', 'Вадим', { id: 'send-home-2' }),
  line('Дмит', 'Лучше пропустить олимпиаду, чем ночью попасться в школе.', 'send-home-4', 'Дмит', 'Вадим', { id: 'send-home-3' }),
  line('Вадим', 'Ты сам недавно убегал из школы.', 'send-home-5', 'Дмит', 'Вадим', { id: 'send-home-4' }),
  line('Дмит', 'Поэтому и говорю.', 'send-home-6', 'Дмит', 'Мишган', { id: 'send-home-5' }),
  line('Мишган', 'Опытный человек.', 'send-home-7', 'Кед', 'Мишган', { id: 'send-home-6' }),
  line('Кед', 'Родители, может, позвонят учителю.', 'send-home-8', 'Кед', 'Вадим', { id: 'send-home-7' }),
  line('Вадим', 'Отец будет очень зол.', 'send-home-9', 'Дмит', 'Вадим', { id: 'send-home-8' }),
  line('Дмит', 'Будет. Потом перестанет.', 'send-home-10', 'Дмит', 'Вадим', { id: 'send-home-9' }),
  line('Вадим', 'Ты не знаешь моего отца.', 'send-home-11', 'Дмит', 'Вадим', { id: 'send-home-10' }),
  line('Дмит', 'Ты моего тоже не знаешь.', 'send-home-12', 'Дмит', 'Вадим', { id: 'send-home-11' }),
  line('Рассказчик', 'Вадим смотрит на закрытые школьные окна, затем поднимает велосипед.', 'send-home-13', 'Дмит', 'Вадим', { id: 'send-home-12' }),
  line('Вадим', 'Хорошо. Но мне нужна помощь с цепью.', 'send-home-14', 'Кед', 'Вадим', { id: 'send-home-13' }),
  line('Кед', 'Дотащим.', 'send-home-15', 'Кед', 'Данз', { id: 'send-home-14' }),
  line('Данз', 'Можно на буксир.', 'send-home-16', 'Кед', 'Данз', { id: 'send-home-15' }),
  line('Кед', 'Чем?', 'send-home-17', 'Кед', 'Данз', { id: 'send-home-16' }),
  line('Данз', 'Мной.', 'send-home-18', 'Кед', 'Данз', { id: 'send-home-17' }),
  line('Кед', 'Ты не вывезешь.', 'stage-end-home', 'Кед', 'Данз', { id: 'send-home-18' }),

  line('Дмит', 'Это не моя проблема. Сам рюкзак забыл — сам и разбирайся.', 'refuse-2', 'Дмит', 'Вадим', { id: 'refuse-1' }),
  line('Вадим', 'Понятно.', 'refuse-3', 'Дмит', 'Вадим', { id: 'refuse-2' }),
  line('Кед', 'Дмит.', 'refuse-4', 'Дмит', 'Кед', { id: 'refuse-3' }),
  line('Дмит', 'Чё?', 'refuse-5', 'Дмит', 'Кед', { id: 'refuse-4' }),
  line('Кед', 'Он мелкий.', 'refuse-6', 'Дмит', 'Кед', { id: 'refuse-5' }),
  line('Дмит', 'И чё? Мы теперь всех по району спасаем?', 'refuse-7', 'Дмит', 'Мишган', { id: 'refuse-6' }),
  line('Мишган', 'Не всех. Только тех, кто рядом.', 'refuse-8', 'Дмит', 'Мишган', { id: 'refuse-7' }),
  line('Дмит', 'Сам помогай.', 'refuse-9', 'Мишган', 'Вадим', { id: 'refuse-8' }),
  line('Мишган', 'Помогу.', 'refuse-10', 'Мишган', 'Вадим', { id: 'refuse-9' }),
  line('Вадим', 'Не надо спорить. Я сам.', 'refuse-11', 'Данз', 'Вадим', { id: 'refuse-10' }),
  line('Данз', 'Ты реально полезешь?', 'refuse-12', 'Дмит', 'Вадим', { id: 'refuse-11' }),
  line('Вадим', 'Да.', 'refuse-13', 'Дмит', 'Вадим', { id: 'refuse-12' }),
  line('Дмит', 'Ну вот. Разобрались.', 'refuse-14', 'Дмит', 'Вадим', { id: 'refuse-13' }),
  line('Рассказчик', 'Вадим отворачивается к велосипеду. Кед и Мишган смотрят на Дмита уже не так весело, как несколько минут назад.', 'stage-end-refuse', 'Дмит', 'Вадим', { id: 'refuse-14' }),

  line('Дмит', 'Забей на рюкзак. Пошли с нами гулять.', 'night-walk-2', 'Дмит', 'Вадим', { id: 'night-walk-1' }),
  line('Вадим', 'Куда?', 'night-walk-3', 'Дмит', 'Вадим', { id: 'night-walk-2' }),
  line('Дмит', 'По району.', 'night-walk-4', 'Дмит', 'Вадим', { id: 'night-walk-3' }),
  line('Вадим', 'Сейчас почти десять.', 'night-walk-5', 'Данз', 'Вадим', { id: 'night-walk-4' }),
  line('Данз', 'Самое время.', 'night-walk-6', 'Данз', 'Вадим', { id: 'night-walk-5' }),
  line('Вадим', 'Для чего?', 'night-walk-7', 'Данз', 'Вадим', { id: 'night-walk-6' }),
  line('Данз', 'Для района.', 'night-walk-8', 'Кед', 'Данз', { id: 'night-walk-7' }),
  line('Кед', 'Не слушай его.', 'night-walk-9', 'Дмит', 'Вадим', { id: 'night-walk-8' }),
  line('Вадим', 'А документы?', 'night-walk-10', 'Дмит', 'Вадим', { id: 'night-walk-9' }),
  line('Дмит', 'Утром заберёшь.', 'night-walk-11', 'Дмит', 'Вадим', { id: 'night-walk-10' }),
  line('Вадим', 'Я объяснил, почему не смогу.', 'night-walk-12', 'Дмит', 'Вадим', { id: 'night-walk-11' }),
  line('Дмит', 'Ну один раз олимпиаду пропустишь.', 'night-walk-13', 'Дмит', 'Вадим', { id: 'night-walk-12' }),
  line('Вадим', 'Я готовился три месяца.', 'night-walk-14', 'Данз', 'Вадим', { id: 'night-walk-13' }),
  line('Данз', 'Я к выборам мэра тоже долго готовился.', 'night-walk-15', 'Данз', 'Вадим', { id: 'night-walk-14' }),
  line('Вадим', 'Ты подкупил игроков.', 'night-walk-16', 'Данз', 'Вадим', { id: 'night-walk-15' }),
  line('Данз', 'Это политика.', 'night-walk-17', 'Дмит', 'Вадим', { id: 'night-walk-16' }),
  line('Дмит', 'Короче, решай. Один здесь останешься или с нами пойдёшь.', 'night-walk-18', 'Дмит', 'Вадим', { id: 'night-walk-17' }),
  line('Рассказчик', 'Вадим смотрит на тёмную школу, сломанный велосипед и компанию старших ребят.', 'night-walk-19', 'Дмит', 'Вадим', { id: 'night-walk-18' }),
  line('Вадим', 'Только ненадолго.', 'night-walk-20', 'Дмит', 'Вадим', { id: 'night-walk-19' }),
  line('Дмит', 'Конечно.', 'night-walk-21', 'Дмит', 'Вадим', { id: 'night-walk-20' }),
  line('Рассказчик', 'Вадим делает шаг за компанией. Школа остаётся за спиной, но рюкзак всё ещё лежит внутри, как маленькая мина замедленного действия.', 'stage-end-walk', 'Дмит', 'Вадим', { id: 'night-walk-21' }),

  line('Рассказчик', 'Учитель неожиданно отвечает. Голос сонный, злой, но живой. Вадим быстро объясняет ситуацию, а Дмит впервые за вечер молчит так полезно, что это почти взрослая позиция.', 'teacher-call-success-2', 'Дмит', 'Вадим', { id: 'teacher-call-success-1' }),
  line('Вадим', 'Он сказал, что подъедет к школе через двадцать минут.', 'teacher-call-success-3', 'Дмит', 'Вадим', { id: 'teacher-call-success-2' }),
  line('Дмит', 'Вот. Законно, скучно, зато без забора.', 'stage-end-teacher', 'Дмит', 'Вадим', { id: 'teacher-call-success-3' }),
  line('Вадим', 'Учитель не отвечает.', 'teacher-call-fail-2', 'Дмит', 'Вадим', { id: 'teacher-call-fail-1' }),
  line('Дмит', 'Значит, законный путь умер первым.', 'main-choice', 'Дмит', 'Вадим', { id: 'teacher-call-fail-2' }),

  line('Дмит', 'Сначала разберёмся, кто трогал твой велосипед.', 'bike-sabotage-sidequest-2', 'Дмит', 'Вадим', { id: 'bike-sabotage-sidequest-1' }),
  line('Вадим', 'Ты думаешь, это важно?', 'bike-sabotage-sidequest-3', 'Дмит', 'Вадим', { id: 'bike-sabotage-sidequest-2' }),
  line('Дмит', 'Если кто-то сорвал цепь специально, он мог ждать, что ты вернёшься к школе.', 'bike-sabotage-sidequest-4', 'Кед', 'Вадим', { id: 'bike-sabotage-sidequest-3' }),
  line('Кед', 'И вот это уже пахнет не велосипедом, а засадой.', 'stage-end-sabotage', 'Кед', 'Вадим', { id: 'bike-sabotage-sidequest-4' }),

  line('Рассказчик', 'Компания подходит ближе к школе. Теперь это уже не разговор у забора, а почти план — просто пока без той части, где кто-нибудь понимает, что делает.', 'infiltration-1', 'Дмит', 'Вадим', {
    id: 'stage-end-infiltration',
    effects: {
      experience: 5,
      flags: ['CHAPTER_1_SMALL_SCHOOL_BACKPACK_STORY', 'CHAPTER_1_SMALL_SCHOOL_PLAN_CREATED'],
    },
  }),

  line('Рассказчик', 'Дмит ещё раз смотрит на тёмные окна школы. Свет горит только на первом этаже — возле главного входа и в коридоре рядом с учительской.', 'infiltration-2', 'Дмит', 'Вадим', { id: 'infiltration-1' }),
  line('Дмит', 'Так. Сначала решаем, как входим.', 'infiltration-3', 'Дмит', 'Вадим', { id: 'infiltration-2' }),
  line('Вадим', 'Я предлагаю через окно раздевалки.', 'infiltration-4', 'Дмит', 'Вадим', { id: 'infiltration-3' }),
  line('Кед', 'А если оно закрыто?', 'infiltration-5', 'Кед', 'Вадим', { id: 'infiltration-4' }),
  line('Вадим', 'Тогда придётся выбрать другой путь.', 'infiltration-6', 'Данз', 'Вадим', { id: 'infiltration-5' }),
  line('Данз', 'Или разбить его камнем.', 'infiltration-7', 'Данз', 'Вадим', { id: 'infiltration-6' }),
  line('Вадим', 'Нет.', 'infiltration-8', 'Данз', 'Вадим', { id: 'infiltration-7' }),
  line('Данз', 'Почему сразу нет?', 'infiltration-9', 'Данз', 'Вадим', { id: 'infiltration-8' }),
  line('Вадим', 'Потому что разбитое окно обычно замечают.', 'infiltration-10', 'Данз', 'Вадим', { id: 'infiltration-9' }),
  line('Данз', 'А если разбить очень аккуратно?', 'infiltration-11', 'Кед', 'Данз', { id: 'infiltration-10' }),
  line('Кед', 'Ты даже упал сегодня неаккуратно.', 'infiltration-12', 'Данз', 'Мишган', { id: 'infiltration-11' }),
  line('Мишган', 'Он не упал. Он провёл удар ногой по мне, а потом принял горизонтальную стойку.', 'infiltration-13', 'Данз', 'Мишган', { id: 'infiltration-12' }),
  line('Данз', 'Звучит профессионально.', 'infiltration-14', 'Данз', 'Мишган', { id: 'infiltration-13' }),
  line('Мишган', 'Нога до сих пор не согласна.', 'infiltration-15', 'Дмит', 'Мишган', { id: 'infiltration-14' }),
  line('Дмит', 'Тихо. Нам рюкзак забрать надо, а не ещё один бой начать.', 'infiltration-16', 'Дмит', 'Вадим', { id: 'infiltration-15' }),
  line('Вадим', 'У школы четыре возможных входа.', 'infiltration-17', 'Дмит', 'Вадим', { id: 'infiltration-16' }),
  line('Дмит', 'Откуда знаешь?', 'infiltration-18', 'Дмит', 'Вадим', { id: 'infiltration-17' }),
  line('Вадим', 'Я здесь учусь.', 'infiltration-19', 'Дмит', 'Вадим', { id: 'infiltration-18' }),
  line('Дмит', 'Я тоже здесь учусь.', 'infiltration-20', 'Дмит', 'Вадим', { id: 'infiltration-19' }),
  line('Вадим', 'Ты однажды искал кабинет химии на третьем этаже.', 'infiltration-21', 'Дмит', 'Вадим', { id: 'infiltration-20' }),
  line('Дмит', 'И чё?', 'infiltration-22', 'Данз', 'Вадим', { id: 'infiltration-21' }),
  line('Вадим', 'Он находится на втором.', 'infiltration-23', 'Данз', 'Вадим', { id: 'infiltration-22' }),
  line('Данз', 'Он тебя опять.', 'infiltration-24', 'Дмит', 'Данз', { id: 'infiltration-23' }),
  {
    id: 'infiltration-24',
    speaker: 'Дмит',
    text: 'Да понял я.',
    left: 'Дмит',
    right: 'Вадим',
    background: 'school-dark-vaz',
    choices: [
      { label: 'Ты умный — ты и говори, куда лезть.', shortLabel: 'Пусть Вадим ведёт.', next: 'entry-neutral-smart-1' },
      { label: 'Без лекций. Покажи самый быстрый вход.', shortLabel: 'Самый быстрый вход.', next: 'entry-neutral-fast-1' },
      { label: 'Сейчас сами разберёмся. Мы тут старшие.', shortLabel: 'Мы тут старшие.', next: 'entry-neutral-older-1' },
      { label: 'Давайте сначала спокойно всё проверим.', shortLabel: 'Спокойно проверить.', next: 'entry-neutral-calm-1' },
    ],
  },

  line('Дмит', 'Ты умный — ты и говори, куда лезть.', 'entry-neutral-smart-2', 'Дмит', 'Вадим', { id: 'entry-neutral-smart-1' }),
  line('Вадим', 'Умный человек предложил бы пойти домой.', 'entry-neutral-smart-3', 'Дмит', 'Вадим', { id: 'entry-neutral-smart-2' }),
  line('Дмит', 'Не настолько умный.', 'entry-neutral-smart-4', 'Дмит', 'Вадим', { id: 'entry-neutral-smart-3' }),
  line('Вадим', 'Тогда окно раздевалки.', 'entry-neutral-smart-5', 'Мишган', 'Вадим', { id: 'entry-neutral-smart-4' }),
  line('Мишган', 'Хорошая корректировка плана.', 'risk-route', 'Дмит', 'Вадим', { id: 'entry-neutral-smart-5' }),

  line('Дмит', 'Без лекций. Покажи самый быстрый вход.', 'entry-neutral-fast-2', 'Дмит', 'Вадим', { id: 'entry-neutral-fast-1' }),
  line('Вадим', 'Самый быстрый не обязательно самый безопасный.', 'entry-neutral-fast-3', 'Дмит', 'Вадим', { id: 'entry-neutral-fast-2' }),
  line('Дмит', 'Вадим.', 'entry-neutral-fast-4', 'Дмит', 'Вадим', { id: 'entry-neutral-fast-3' }),
  line('Вадим', 'Хорошо. Самый быстрый — через окно раздевалки.', 'entry-neutral-fast-5', 'Данз', 'Вадим', { id: 'entry-neutral-fast-4' }),
  line('Данз', 'Вот. Мог же коротко.', 'risk-route', 'Дмит', 'Вадим', { id: 'entry-neutral-fast-5' }),

  line('Дмит', 'Сейчас сами разберёмся. Мы тут старшие.', 'entry-neutral-older-2', 'Дмит', 'Вадим', { id: 'entry-neutral-older-1' }),
  line('Вадим', 'Возраст не гарантирует правильных решений.', 'entry-neutral-older-3', 'Дмит', 'Вадим', { id: 'entry-neutral-older-2' }),
  line('Дмит', 'Зато даёт право уверенно ошибаться.', 'entry-neutral-older-4', 'Дмит', 'Кед', { id: 'entry-neutral-older-3' }),
  line('Кед', 'Сильная взрослая позиция.', 'entry-neutral-older-5', 'Кед', 'Вадим', { id: 'entry-neutral-older-4' }),
  line('Вадим', 'Я начинаю беспокоиться.', 'risk-route', 'Дмит', 'Вадим', { id: 'entry-neutral-older-5' }),

  line('Дмит', 'Давайте сначала спокойно всё проверим.', 'entry-neutral-calm-2', 'Дмит', 'Вадим', { id: 'entry-neutral-calm-1' }),
  line('Вадим', 'Это разумно.', 'entry-neutral-calm-3', 'Дмит', 'Данз', { id: 'entry-neutral-calm-2' }),
  line('Данз', 'Дмит, ты точно пил?', 'entry-neutral-calm-4', 'Дмит', 'Данз', { id: 'entry-neutral-calm-3' }),
  line('Дмит', 'Ещё слово — будешь проверять забор головой.', 'entry-neutral-calm-5', 'Дмит', 'Кед', { id: 'entry-neutral-calm-4' }),
  line('Кед', 'Всё, снова он.', 'risk-route', 'Дмит', 'Вадим', { id: 'entry-neutral-calm-5' }),

  line('Рассказчик', 'Компания замирает у школьной территории и ещё раз осматривается.', 'entry-main-talk-1', 'Дмит', 'Вадим', {
    id: 'risk-route',
    nextByFlag: [
      { flag: 'MATVEY_CREW_MAY_FIND_SCHOOL', next: 'matvey-scout-1' },
      { flag: 'UNKNOWN_GIRL_INTEREST', next: 'unknown-phone-1' },
    ],
    fallbackNext: 'entry-main-talk-1',
  }),

  line('Рассказчик', 'На другой стороне дороги появляется силуэт. Парень останавливается возле автобусной остановки и некоторое время смотрит в сторону школы.', 'matvey-scout-2', 'Дмит', 'Кед', { id: 'matvey-scout-1' }),
  line('Кед', 'Вон тот на нас смотрит.', 'matvey-scout-3', 'Дмит', 'Кед', { id: 'matvey-scout-2' }),
  line('Дмит', 'Который?', 'matvey-scout-4', 'Дмит', 'Кед', { id: 'matvey-scout-3' }),
  line('Кед', 'У остановки.', 'matvey-scout-5', 'Кед', 'Мишган', { id: 'matvey-scout-4' }),
  line('Мишган', 'Он был с Матвеем.', 'matvey-scout-6', 'Дмит', 'Мишган', { id: 'matvey-scout-5' }),
  line('Дмит', 'Точно?', 'matvey-scout-7', 'Дмит', 'Мишган', { id: 'matvey-scout-6' }),
  line('Мишган', 'Я лица противников запоминаю.', 'matvey-scout-8', 'Данз', 'Мишган', { id: 'matvey-scout-7' }),
  line('Данз', 'А девушек?', 'matvey-scout-9', 'Данз', 'Мишган', { id: 'matvey-scout-8' }),
  line('Мишган', 'Тоже.', 'matvey-scout-10', 'Данз', 'Мишган', { id: 'matvey-scout-9' }),
  line('Данз', 'Это уже не бокс.', 'matvey-scout-11', 'Данз', 'Вадим', { id: 'matvey-scout-10' }),
  line('Вадим', 'Он достал телефон.', 'matvey-scout-12', 'Дмит', 'Вадим', { id: 'matvey-scout-11' }),
  line('Дмит', 'Может, просто кому-то звонит.', 'matvey-scout-13', 'Дмит', 'Вадим', { id: 'matvey-scout-12' }),
  line('Вадим', 'Он направил камеру на школу.', 'matvey-scout-14', 'Данз', 'Вадим', { id: 'matvey-scout-13' }),
  line('Данз', 'Может, фотографирует архитектуру.', 'matvey-scout-15', 'Кед', 'Данз', { id: 'matvey-scout-14' }),
  line('Кед', 'Ночью?', 'matvey-scout-16', 'Кед', 'Данз', { id: 'matvey-scout-15' }),
  line('Данз', 'Творческие люди странные.', 'matvey-scout-17', 'Мишган', 'Данз', { id: 'matvey-scout-16' }),
  line('Мишган', 'Это разведчик, бля.', 'matvey-scout-18', 'Дмит', 'Мишган', { id: 'matvey-scout-17' }),
  line('Дмит', 'Пусть смотрит.', 'matvey-scout-19', 'Дмит', 'Вадим', { id: 'matvey-scout-18' }),
  line('Вадим', 'Если он сообщит охраннику, что мы собираемся проникнуть в школу, тот будет смотреть внимательнее.', 'matvey-scout-20', 'Дмит', 'Вадим', { id: 'matvey-scout-19' }),
  line('Дмит', 'Тогда заходим быстрее.', 'matvey-scout-21', 'Дмит', 'Вадим', { id: 'matvey-scout-20' }),
  line('Вадим', 'Это не решает проблему.', 'matvey-scout-22', 'Дмит', 'Вадим', { id: 'matvey-scout-21' }),
  line('Дмит', 'Зато звучит как план.', 'matvey-scout-23', 'Дмит', 'Вадим', { id: 'matvey-scout-22' }),
  line('Рассказчик', 'Парень что-то говорит по телефону, после чего медленно уходит за остановку.', 'after-scout-route', 'Дмит', 'Вадим', {
    id: 'matvey-scout-23',
    effects: { flags: ['MATVEY_SCOUT_SAW_GROUP'] },
  }),
  line('Рассказчик', 'После силуэта у остановки школьный двор кажется ещё тише.', 'entry-main-talk-1', 'Дмит', 'Вадим', {
    id: 'after-scout-route',
    nextByFlag: [
      { flag: 'UNKNOWN_GIRL_INTEREST', next: 'unknown-phone-1' },
    ],
    fallbackNext: 'entry-main-talk-1',
  }),

  {
    id: 'unknown-phone-1',
    speaker: '???',
    text: 'Матвей ищет вас. Один из его друзей пошёл к школе.',
    left: 'Дмит',
    background: 'school-dark-vaz',
    sound: 'phone-vibrate',
    phoneMessage: { contact: 'Неизвестный номер', direction: 'incoming', time: '21:54' },
    next: 'unknown-after-1',
  },
  line('Дмит', 'Охуеть.', 'unknown-after-2', 'Дмит', 'Кед', { id: 'unknown-after-1' }),
  line('Кед', 'Чё там?', 'unknown-after-3', 'Дмит', 'Кед', { id: 'unknown-after-2' }),
  line('Дмит', 'Девчонка с Миньки.', 'unknown-after-4', 'Дмит', 'Данз', { id: 'unknown-after-3' }),
  line('Данз', 'Она уже пишет?!', 'unknown-after-5', 'Дмит', 'Данз', { id: 'unknown-after-4' }),
  line('Дмит', 'Не ори.', 'unknown-after-6', 'Дмит', 'Данз', { id: 'unknown-after-5' }),
  line('Данз', 'А чё она написала?', 'unknown-after-7', 'Дмит', 'Данз', { id: 'unknown-after-6' }),
  line('Дмит', 'Матвей нас ищет.', 'unknown-after-8', 'Дмит', 'Мишган', { id: 'unknown-after-7' }),
  line('Мишган', 'А про меня что-нибудь?', 'unknown-after-9', 'Дмит', 'Мишган', { id: 'unknown-after-8' }),
  line('Дмит', 'Нет.', 'unknown-after-10', 'Дмит', 'Мишган', { id: 'unknown-after-9' }),
  line('Мишган', 'Странно. Я там лучше всех работал.', 'unknown-after-11', 'Мишган', 'Вадим', { id: 'unknown-after-10' }),
  line('Вадим', 'Почему Матвей вас ищет?', 'unknown-after-12', 'Кед', 'Вадим', { id: 'unknown-after-11' }),
  line('Кед', 'У них был конфликт.', 'unknown-after-13', 'Данз', 'Вадим', { id: 'unknown-after-12' }),
  line('Данз', 'Территориальный спор между двумя влиятельными группировками.', 'unknown-after-14', 'Дмит', 'Данз', { id: 'unknown-after-13' }),
  line('Дмит', 'Не слушай его.', 'unknown-after-15', 'Мишган', 'Вадим', { id: 'unknown-after-14' }),
  line('Вадим', 'Кто победил?', 'unknown-after-16', 'Мишган', 'Вадим', { id: 'unknown-after-15' }),
  line('Мишган', 'Мы.', 'unknown-after-17', 'Кед', 'Вадим', { id: 'unknown-after-16' }),
  line('Кед', 'Смотря какой исход считать победой.', 'unknown-after-18', 'Дмит', 'Вадим', { id: 'unknown-after-17' }),
  line('Дмит', 'Короче, за нами могут прийти.', 'unknown-after-19', 'Дмит', 'Вадим', { id: 'unknown-after-18' }),
  line('Вадим', 'Тогда нам точно не стоит стоять возле главного входа.', 'unknown-after-20', 'Дмит', 'Вадим', { id: 'unknown-after-19' }),
  line('Рассказчик', 'Дмит быстро печатает ответ.', 'unknown-phone-2', 'Дмит', undefined, { id: 'unknown-after-20' }),
  {
    id: 'unknown-phone-2',
    speaker: 'Дмит',
    text: 'Спасибо. Ты где?',
    left: 'Дмит',
    background: 'school-dark-vaz',
    phoneMessage: { contact: 'Неизвестный номер', direction: 'outgoing', time: '21:55' },
    next: 'unknown-phone-3',
  },
  {
    id: 'unknown-phone-3',
    speaker: '???',
    text: 'Неважно. Не стойте у главного входа.',
    left: 'Дмит',
    background: 'school-dark-vaz',
    phoneMessage: { contact: 'Неизвестный номер', direction: 'incoming', time: '21:55' },
    next: 'unknown-phone-4',
  },
  {
    id: 'unknown-phone-4',
    speaker: 'Дмит',
    text: 'Почему?',
    left: 'Дмит',
    background: 'school-dark-vaz',
    phoneMessage: { contact: 'Неизвестный номер', direction: 'outgoing', time: '21:55' },
    next: 'unknown-phone-read',
  },
  {
    id: 'unknown-phone-read',
    speaker: 'Рассказчик',
    text: 'Сообщение прочитано, но девушка больше не отвечает.',
    left: 'Дмит',
    background: 'school-dark-vaz',
    phoneMessage: { contact: 'Неизвестный номер', direction: 'incoming', time: '21:55' },
    next: 'unknown-after-21',
  },
  line('Данз', 'Таинственная.', 'unknown-after-22', 'Данз', 'Мишган', { id: 'unknown-after-21' }),
  line('Мишган', 'Работает из тени.', 'unknown-after-23', 'Кед', 'Мишган', { id: 'unknown-after-22' }),
  line('Кед', 'Или просто не хочет с Дмитом разговаривать.', 'unknown-after-24', 'Дмит', 'Кед', { id: 'unknown-after-23' }),
  line('Дмит', 'Завали.', 'entry-main-talk-1', 'Дмит', 'Вадим', {
    id: 'unknown-after-24',
    effects: { flags: ['GIRL_WARNED_ABOUT_MATVEY'] },
  }),

  line('Вадим', 'Главный вход закрыт. Охранник находится возле вахты.', 'entry-main-talk-2', 'Дмит', 'Вадим', { id: 'entry-main-talk-1' }),
  line('Дмит', 'Можно с ним поговорить.', 'entry-main-talk-3', 'Дмит', 'Кед', { id: 'entry-main-talk-2' }),
  line('Кед', 'Можно не разговаривать и залезть с другой стороны.', 'entry-main-talk-4', 'Кед', 'Мишган', { id: 'entry-main-talk-3' }),
  line('Мишган', 'Можно вызвать его на честный поединок.', 'entry-main-talk-5', 'Мишган', 'Вадим', { id: 'entry-main-talk-4' }),
  line('Вадим', 'Нельзя.', 'entry-main-talk-6', 'Мишган', 'Вадим', { id: 'entry-main-talk-5' }),
  line('Мишган', 'Почему?', 'entry-main-talk-7', 'Мишган', 'Вадим', { id: 'entry-main-talk-6' }),
  line('Вадим', 'Потому что нам нужен рюкзак, а не новый разговор с директором.', 'entry-main-talk-8', 'Данз', 'Вадим', { id: 'entry-main-talk-7' }),
  line('Данз', 'Я могу отвлечь охранника.', 'entry-main-talk-9', 'Данз', 'Вадим', { id: 'entry-main-talk-8' }),
  line('Рассказчик', 'Все: Нет.', 'entry-main-talk-10', 'Кед', 'Данз', { id: 'entry-main-talk-9' }),
  line('Данз', 'Вы даже не знаете как.', 'entry-main-talk-11', 'Кед', 'Данз', { id: 'entry-main-talk-10' }),
  line('Кед', 'Именно поэтому нет.', 'entry-main-talk-12', 'Кед', 'Данз', { id: 'entry-main-talk-11' }),
  line('Данз', 'Я мог бы притвориться потерявшимся ребёнком.', 'entry-main-talk-13', 'Дмит', 'Данз', { id: 'entry-main-talk-12' }),
  line('Дмит', 'Ты выше половины учителей.', 'entry-main-talk-14', 'Дмит', 'Данз', { id: 'entry-main-talk-13' }),
  line('Данз', 'Поздно развился.', 'pre-entry-choice', 'Дмит', 'Вадим', { id: 'entry-main-talk-14' }),
  {
    id: 'pre-entry-choice',
    speaker: 'Рассказчик',
    text: 'Перед главным решением Дмит может раздать роли. Или хотя бы попытаться сделать вид, что роли тут вообще есть.',
    left: 'Дмит',
    right: 'Вадим',
    background: 'school-dark-vaz',
    choices: [
      { label: 'Данз, твоя задача — вообще ничего не делать.', shortLabel: 'Данз ничего не делает.', next: 'pre-entry-danz-1' },
      { label: 'Кед, следи за Данзом. Это важнее охранника.', shortLabel: 'Кед следит за Данзом.', next: 'pre-entry-ked-1' },
      { label: 'Мишган, руками никого не трогаем.', shortLabel: 'Мишган без ударов.', next: 'pre-entry-mishgan-1' },
      { label: 'Вадим, последний шанс передумать.', shortLabel: 'Последний шанс Вадиму.', next: 'pre-entry-vadim-1' },
    ],
  },
  line('Дмит', 'Данз, твоя задача — вообще ничего не делать.', 'pre-entry-danz-2', 'Дмит', 'Данз', { id: 'pre-entry-danz-1' }),
  line('Данз', 'Я умею.', 'pre-entry-danz-3', 'Кед', 'Данз', { id: 'pre-entry-danz-2' }),
  line('Кед', 'Нет.', 'pre-entry-danz-4', 'Кед', 'Данз', { id: 'pre-entry-danz-3' }),
  line('Данз', 'Я каждый урок так делаю.', 'pre-entry-danz-5', 'Данз', 'Вадим', { id: 'pre-entry-danz-4' }),
  line('Вадим', 'Это правда.', 'entry-choice', 'Дмит', 'Вадим', { id: 'pre-entry-danz-5' }),
  line('Дмит', 'Кед, следи за Данзом. Это важнее охранника.', 'pre-entry-ked-2', 'Кед', 'Данз', { id: 'pre-entry-ked-1' }),
  line('Кед', 'Я не нянька.', 'pre-entry-ked-3', 'Кед', 'Данз', { id: 'pre-entry-ked-2' }),
  line('Данз', 'А на руках понесёшь?', 'pre-entry-ked-4', 'Кед', 'Данз', { id: 'pre-entry-ked-3' }),
  line('Кед', 'Могу. До мусорки.', 'entry-choice', 'Дмит', 'Вадим', { id: 'pre-entry-ked-4' }),
  line('Дмит', 'Мишган, руками никого не трогаем.', 'pre-entry-mishgan-2', 'Дмит', 'Мишган', { id: 'pre-entry-mishgan-1' }),
  line('Мишган', 'А если он первый?', 'pre-entry-mishgan-3', 'Дмит', 'Мишган', { id: 'pre-entry-mishgan-2' }),
  line('Дмит', 'Тоже.', 'pre-entry-mishgan-4', 'Мишган', 'Вадим', { id: 'pre-entry-mishgan-3' }),
  line('Мишган', 'Сложные правила.', 'pre-entry-mishgan-5', 'Мишган', 'Вадим', { id: 'pre-entry-mishgan-4' }),
  line('Вадим', 'На самом деле довольно простые.', 'entry-choice', 'Дмит', 'Вадим', { id: 'pre-entry-mishgan-5' }),
  line('Дмит', 'Вадим, последний шанс передумать.', 'pre-entry-vadim-2', 'Дмит', 'Вадим', { id: 'pre-entry-vadim-1' }),
  line('Вадим', 'Я уже сорок минут пытаюсь попасть внутрь.', 'pre-entry-vadim-3', 'Дмит', 'Вадим', { id: 'pre-entry-vadim-2' }),
  line('Дмит', 'Это не ответ.', 'pre-entry-vadim-4', 'Дмит', 'Вадим', { id: 'pre-entry-vadim-3' }),
  line('Вадим', 'Не передумал.', 'pre-entry-vadim-5', 'Дмит', 'Вадим', { id: 'pre-entry-vadim-4' }),
  line('Дмит', 'Ну тогда погнали.', 'entry-choice', 'Дмит', 'Вадим', { id: 'pre-entry-vadim-5' }),
  {
    id: 'entry-choice',
    speaker: 'Рассказчик',
    text: 'Теперь нужно выбрать способ проникновения. У каждого варианта есть своя цена: деньги, риск, шум, охранник или Данз, что иногда одно и то же.',
    left: 'Дмит',
    right: 'Вадим',
    background: 'school-dark-vaz',
    choices: [
      {
        label: '[Харизма 5] Скажем, что в рюкзаке лекарства. Охранник сам откроет.',
        shortLabel: 'Уговорить охранника.',
        requires: { charisma: 5 },
        next: 'entry-guard-talk-1',
        failNext: 'entry-guard-talk-fail-1',
        failureText: 'Дмит пытается звучать убедительно, но слово «лекарства» выходит так, будто он сам не знает, от чего они.',
        effects: { experience: 8, flags: ['SMALL_SCHOOL_ENTRY_GUARD_TALK'] },
        failureEffects: { flags: ['SMALL_SCHOOL_GUARD_SUSPICIOUS'] },
      },
      {
        label: '[Деньги 200 ₽] Дадим ему денег. Пять минут нам хватит.',
        shortLabel: 'Подкупить охранника.',
        requiresMoney: 200,
        next: 'entry-bribe-1',
        effects: { money: -200, experience: 6, flags: ['SMALL_SCHOOL_ENTRY_BRIBE_GUARD'] },
      },
      {
        label: '[Ловкость 5] Лезем через забор и окно раздевалки.',
        shortLabel: 'Окно раздевалки.',
        requires: { agility: 5 },
        next: 'entry-window-1',
        failNext: 'entry-window-fail-1',
        failureText: 'Дмит примеряется к забору, но ночная школа внезапно становится выше, чем казалась в разговоре.',
        effects: { experience: 8, flags: ['SMALL_SCHOOL_ENTRY_LOCKER_WINDOW'] },
        failureEffects: { flags: ['SMALL_SCHOOL_WINDOW_ATTEMPT_FAILED'] },
      },
      {
        label: '[Интеллект 6] Выключим свет снаружи. Охранник сам выйдет к щитку.',
        shortLabel: 'Отвлечь светом.',
        requires: { intelligence: 6 },
        next: 'entry-lights-1',
        failNext: 'entry-lights-fail-1',
        failureText: 'Дмит объясняет план со щитком, но на середине понимает, что щиток он видел только в кино и один раз на подъезде.',
        effects: { experience: 10, flags: ['SMALL_SCHOOL_ENTRY_LIGHTS_DISTRACTION'] },
        failureEffects: { flags: ['SMALL_SCHOOL_LIGHTS_PLAN_FAILED'] },
      },
      {
        label: '[Сила 6] Сломаем старую решётку у подсобки.',
        shortLabel: 'Решётка подсобки.',
        requires: { strength: 6 },
        next: 'entry-grate-1',
        failNext: 'entry-grate-fail-1',
        failureText: 'Дмит берётся за решётку, но та держится так уверенно, будто её ставили не строители, а обиженный физрук.',
        effects: { experience: 8, flags: ['SMALL_SCHOOL_ENTRY_STORAGE_GRATE', 'SMALL_SCHOOL_ALARM_RISK'] },
        failureEffects: { flags: ['SMALL_SCHOOL_GRATE_NOISE'] },
      },
      {
        label: '[Внимательность 5] К главному входу не идём. Там нас уже могут ждать.',
        shortLabel: 'Избежать главного входа.',
        requires: { perception: 5 },
        requiresFlags: ['GIRL_WARNED_ABOUT_MATVEY'],
        next: 'entry-safe-window-1',
        effects: { experience: 10, flags: ['SMALL_SCHOOL_AVOIDED_MAIN_AMBUSH', 'SMALL_SCHOOL_ENTRY_LOCKER_WINDOW'] },
      },
    ],
  },
  line('Рассказчик', 'Дмит решает попробовать разговор. Если охранник поверит в историю про лекарства, школа сама откроет дверь, будто у неё внезапно появилась совесть.', 'entry-route-end', 'Дмит', 'Вадим', { id: 'entry-guard-talk-1' }),
  line('Рассказчик', 'Охранник настораживается. Теперь главный вход становится хуже, чем был: дверь закрыта, а взгляд за стеклом уже ищет виноватых.', 'entry-route-end', 'Дмит', 'Вадим', { id: 'entry-guard-talk-fail-1' }),
  line('Рассказчик', 'Дмит выбирает старый районный метод: деньги вместо объяснений. Пять минут стоят двести рублей и немного самоуважения.', 'entry-route-end', 'Дмит', 'Вадим', { id: 'entry-bribe-1' }),
  line('Рассказчик', 'План простой: забор, окно раздевалки и тишина. Вадим кивает так серьёзно, будто сейчас начинается олимпиада по незаконному проникновению.', 'entry-route-end', 'Дмит', 'Вадим', { id: 'entry-window-1' }),
  line('Рассказчик', 'Забор не принимает Дмита с первого раза. Кед ловит его за куртку, Данз почти хлопает, но вовремя вспоминает, что они скрываются.', 'entry-route-end', 'Дмит', 'Кед', { id: 'entry-window-fail-1' }),
  line('Рассказчик', 'Дмит выбирает свет. Если вырубить питание снаружи, охранник выйдет к щитку, а школа на пару минут станет темнее и честнее.', 'entry-route-end', 'Дмит', 'Вадим', { id: 'entry-lights-1' }),
  line('Рассказчик', 'План со щитком разваливается ещё до щитка. Вадим тихо предлагает не трогать электричество, пока у всех есть волосы.', 'entry-route-end', 'Дмит', 'Вадим', { id: 'entry-lights-fail-1' }),
  line('Рассказчик', 'Дмит выбирает решётку у подсобки. Это шумно, тупо и потенциально эффективно — идеальное сочетание для вечера, который уже вышел из-под контроля.', 'entry-route-end', 'Дмит', 'Мишган', { id: 'entry-grate-1' }),
  line('Рассказчик', 'Решётка не поддаётся, зато звук получается такой, будто школа кашлянула железом. Где-то внутри охранник наверняка поднял голову.', 'entry-route-end', 'Дмит', 'Вадим', { id: 'entry-grate-fail-1' }),
  line('Рассказчик', 'Дмит решает не идти к главному входу. Предупреждение неизвестной девчонки делает своё дело: компания уходит к раздевалке, пока возможная засада смотрит не туда.', 'entry-route-end', 'Дмит', 'Вадим', { id: 'entry-safe-window-1' }),
  line('Рассказчик', 'Способ выбран. Теперь остаётся самое неприятное: действительно зайти внутрь школы ночью и не превратить это в легенду для педсовета.', '', 'Дмит', 'Вадим', {
    id: 'entry-route-end',
    sound: 'quest-complete',
    effects: {
      experience: 6,
      flags: ['CHAPTER_1_SMALL_SCHOOL_MET_VADIM', 'CHAPTER_1_SMALL_SCHOOL_INFILTRATION_ROUTE_SELECTED'],
    },
  }),
  line('Рассказчик', 'Этап заканчивается безопасным решением: компания помогает Вадиму с велосипедом и ведёт его домой. Школа остаётся закрытой, но живой и без ночного цирка.', '', 'Дмит', 'Вадим', {
    id: 'stage-end-home',
    sound: 'quest-complete',
    effects: {
      experience: 4,
      flags: ['CHAPTER_1_SMALL_SCHOOL_MET_VADIM', 'CHAPTER_1_SMALL_SCHOOL_BACKPACK_STORY', 'CHAPTER_1_SMALL_SCHOOL_SENT_VADIM_HOME'],
    },
  }),
  line('Рассказчик', 'Этап заканчивается отказом. Вадим остаётся у школы, а у Дмита внутри появляется неприятная тишина — такая, которую не перебивает даже Данз.', '', 'Дмит', 'Вадим', {
    id: 'stage-end-refuse',
    sound: 'quest-complete',
    effects: {
      flags: ['CHAPTER_1_SMALL_SCHOOL_MET_VADIM', 'CHAPTER_1_SMALL_SCHOOL_BACKPACK_STORY', 'CHAPTER_1_SMALL_SCHOOL_REFUSED_VADIM'],
    },
  }),
  line('Рассказчик', 'Этап заканчивается ночной прогулкой с Вадимом. Район принимает малого в компанию, а школа остаётся позади тёмной коробкой с чужим рюкзаком внутри.', '', 'Дмит', 'Вадим', {
    id: 'stage-end-walk',
    sound: 'quest-complete',
    effects: {
      flags: ['CHAPTER_1_SMALL_SCHOOL_MET_VADIM', 'CHAPTER_1_SMALL_SCHOOL_BACKPACK_STORY', 'CHAPTER_1_SMALL_SCHOOL_WALK_WITH_VADIM'],
    },
  }),
  line('Рассказчик', 'Этап заканчивается законным решением. Учитель едет к школе, Вадим впервые за вечер выдыхает, а Дмит получает редкий опыт: проблему можно решить без забора.', '', 'Дмит', 'Вадим', {
    id: 'stage-end-teacher',
    sound: 'quest-complete',
    effects: {
      flags: ['CHAPTER_1_SMALL_SCHOOL_MET_VADIM', 'CHAPTER_1_SMALL_SCHOOL_BACKPACK_STORY', 'CHAPTER_1_SMALL_SCHOOL_TEACHER_HELP'],
    },
  }),
  line('Рассказчик', 'Этап сворачивает в сторону расследования: прежде чем лезть в школу, Дмит решает понять, кто сорвал цепь с велосипеда Вадима.', '', 'Дмит', 'Вадим', {
    id: 'stage-end-sabotage',
    sound: 'quest-complete',
    effects: {
      flags: ['CHAPTER_1_SMALL_SCHOOL_MET_VADIM', 'CHAPTER_1_SMALL_SCHOOL_BACKPACK_STORY', 'CHAPTER_1_SMALL_SCHOOL_CHAIN_INVESTIGATION'],
    },
  }),
])
