/* This file is generated by scripts/quest-script.mjs. Do not edit manually. */
import { defineQuest, dialogue, route, setBackground } from "../questDsl"

export const exampleDefinition = defineQuest({
  id: "example",
  start: "morning-corridor",
  nodes: [
  dialogue({
    id: "morning-corridor",
    ...setBackground("school-yard-night"),
    cast: ["Дмит", "Мишган"],
    lines: [
      ["Рассказчик", "Последние школьные дни всегда проходили одинаково."],
      ["Мишган", "Уф-уф, бля. Живой?"],
      ["Дмит", "Был живой, пока ты не заорал."],
    ],
    next: "phone-state",
  }),
  route({
    id: "phone-state",
    routes: [["DMIT_HAS_BLACK_PHONE", "phone-with-dmit"]],
    fallback: "finish",
  }),
  dialogue({
    id: "phone-with-dmit",
    lines: [
      ["Неизвестный номер", "Ты едешь в Строитель?", { sound: "black-phone-vibration", phoneMessage: { contact: "Неизвестный номер", direction: "incoming", time: "08:14" } }],
      ["Дмит", "Ты кто?", { phoneMessage: { contact: "Неизвестный номер", direction: "outgoing", time: "08:14" } }],
      ["Неизвестный номер", "Игоря там не ищи.", { phoneMessage: { contact: "Неизвестный номер", direction: "incoming", time: "08:14" } }],
    ],
    next: "finish",
  }),
  dialogue({
    id: "finish",
    lines: [
      ["Рассказчик", "Утро стало ещё хуже."],
    ],
    end: true,
  })
  ],
})
